// Code generated by MockGen. DO NOT EDIT.
// Source: ../broker/broker.go
//
// Generated by this command:
//
//	mockgen -source=../broker/broker.go -destination=broker_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "example.com/servoorders/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishOrderPlaced mocks base method.
func (m *MockEventPublisher) PublishOrderPlaced(ctx context.Context, o *domain.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOrderPlaced", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOrderPlaced indicates an expected call of PublishOrderPlaced.
func (mr *MockEventPublisherMockRecorder) PublishOrderPlaced(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOrderPlaced", reflect.TypeOf((*MockEventPublisher)(nil).PublishOrderPlaced), ctx, o)
}
