//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// Resolved graph:
//
//	[L1] *example.com/servomocking/realstore.Store
//	      deps: none
//	      capabilities: none | binding: explicit bind | realstore/realstore.go:8:6
//	[L2] *example.com/servomocking/api.Server
//	      deps: *example.com/servomocking/realstore.Store
//	      capabilities: none | binding: sole candidate | api/api.go:7:6
package main

import (
	"context"
	"example.com/servomocking/api"
	"example.com/servomocking/realstore"
	"github.com/okian/servo/v3/servo"
	"os"
	"os/signal"
	"syscall"
)

type App struct {
	store         *realstore.Store
	server        *api.Server
	startupReport servo.StartupReport
}

func New(ctx context.Context) (*App, error) {
	a := &App{}

	store := realstore.New()
	a.store = store

	server := api.New(store)
	a.server = server

	return a, nil
}

func (a *App) Run(ctx context.Context) error {
	return nil
}

func (a *App) Shutdown(ctx context.Context) servo.Report {
	forceExit := make(chan os.Signal, 1)
	signal.Notify(forceExit, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(forceExit)
	watcherDone := make(chan struct{})
	defer close(watcherDone)
	go func() {
		select {
		case <-forceExit:
			os.Exit(1)
		case <-watcherDone:
		}
	}()

	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Health(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Ready(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Graph() servo.Graph {
	return servo.Graph{Nodes: []servo.GraphNode{
		{Type: "*example.com/servomocking/realstore.Store", Level: 1, Deps: nil, Capabilities: nil, Binding: "explicit bind", Pos: "realstore/realstore.go:8:6"},
		{Type: "*example.com/servomocking/api.Server", Level: 2, Deps: []string{"*example.com/servomocking/realstore.Store"}, Capabilities: nil, Binding: "sole candidate", Pos: "api/api.go:7:6"},
	}}
}

func (a *App) Report() servo.StartupReport {
	return a.startupReport
}
