//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// ServoConfig fills Config from the process environment.
// Settings:
//
//	SESSION_RECENT int, default 10
package session

import (
	"fmt"
	"os"
	"strconv"
)

// ServoConfig builds Config. Precedence per setting: default, then the SESSION_* environment
// variable — the environment always wins.
func ServoConfig() (Config, error) {
	var cfg Config

	// recent — SESSION_RECENT
	cfg.Recent = 10
	if v, ok := os.LookupEnv("SESSION_RECENT"); ok {
		val, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return Config{}, fmt.Errorf("SESSION_RECENT: not a valid int: %q", v)
		}
		cfg.Recent = int(val)
	}
	return cfg, nil
}
