// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockstore

import (
	"example.com/servomocking/store"
	"sync"
)

// Ensure, that StoreMock does implement store.Store.
// If this is not the case, regenerate this file with moq.
var _ store.Store = &StoreMock{}

// StoreMock is a mock implementation of store.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked store.Store
//		mockedStore := &StoreMock{
//			GetFunc: func(key string) string {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedStore in code that requires store.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(key string) string

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key string
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *StoreMock) Get(key string) string {
	if mock.GetFunc == nil {
		panic("StoreMock.GetFunc: method is nil but Store.Get was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedStore.GetCalls())
func (mock *StoreMock) GetCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
