//go:build !servoinject && !prod

// Code generated by servo generate. DO NOT EDIT.
//
// Resolved graph:
//
//	[L1] *example.com/servovariants/memory.Mem
//	      deps: none
//	      capabilities: none | binding: explicit bind | memory/memory.go:13:6
//	[L2] *example.com/servovariants/api.Server
//	      deps: *example.com/servovariants/memory.Mem
//	      capabilities: Initializer, Runner | binding: sole candidate | api/api.go:14:6
package main

import (
	"context"
	"errors"
	"os"
	"os/signal"
	"syscall"
	"time"

	"example.com/servovariants/api"
	"example.com/servovariants/memory"
	"github.com/okian/servo/v3/servo"
)

type App struct {
	mem           *memory.Mem
	server        *api.Server
	startupReport servo.StartupReport
}

func New(ctx context.Context) (*App, error) {
	a := &App{}

	mem := memory.New()
	a.mem = mem

	server := api.New(mem)
	a.server = server

	{
		start := time.Now()
		err := a.server.Init(ctx)
		a.startupReport.Nodes = append(a.startupReport.Nodes, servo.StartupNode{Type: "*example.com/servovariants/api.Server", Duration: time.Since(start)})
		if err != nil {
			report := a.Shutdown(ctx)
			return nil, errors.Join(err, report)
		}
	}
	return a, nil
}

func (a *App) Run(ctx context.Context) error {
	return a.server.Run(ctx)
}

func (a *App) Shutdown(ctx context.Context) servo.Report {
	forceExit := make(chan os.Signal, 1)
	signal.Notify(forceExit, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(forceExit)
	watcherDone := make(chan struct{})
	defer close(watcherDone)
	go func() {
		select {
		case <-forceExit:
			os.Exit(1)
		case <-watcherDone:
		}
	}()

	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Health(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Ready(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Graph() servo.Graph {
	return servo.Graph{Nodes: []servo.GraphNode{
		{Type: "*example.com/servovariants/memory.Mem", Level: 1, Deps: nil, Capabilities: nil, Binding: "explicit bind", Pos: "memory/memory.go:13:6"},
		{Type: "*example.com/servovariants/api.Server", Level: 2, Deps: []string{"*example.com/servovariants/memory.Mem"}, Capabilities: []string{"Initializer", "Runner"}, Binding: "sole candidate", Pos: "api/api.go:14:6"},
	}}
}

func (a *App) Report() servo.StartupReport {
	return a.startupReport
}
