//go:build !servoinject && prod

// Code generated by servo generate. DO NOT EDIT.
//
// Resolved graph:
//
//	[L1] *example.com/servovariants/postgres.DB
//	      deps: none
//	      capabilities: Initializer, Finalizer | binding: explicit bind | postgres/postgres.go:13:6
//	[L2] *example.com/servovariants/api.Server
//	      deps: *example.com/servovariants/postgres.DB
//	      capabilities: Initializer, Runner | binding: sole candidate | api/api.go:14:6
package main

import (
	"context"
	"errors"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	"example.com/servovariants/api"
	"example.com/servovariants/postgres"
	"github.com/okian/servo/v3/servo"
)

type App struct {
	db            *postgres.DB
	dbStopOnce    sync.Once
	dbStopResult  servo.NodeResult
	server        *api.Server
	startupReport servo.StartupReport
}

func New(ctx context.Context) (*App, error) {
	a := &App{}

	db := postgres.New()
	a.db = db

	server := api.New(db)
	a.server = server

	{
		start := time.Now()
		err := a.db.Init(ctx)
		a.startupReport.Nodes = append(a.startupReport.Nodes, servo.StartupNode{Type: "*example.com/servovariants/postgres.DB", Duration: time.Since(start)})
		if err != nil {
			report := a.Shutdown(context.WithoutCancel(ctx))
			if report.Clean() {
				return nil, err
			}
			return nil, errors.Join(err, report)
		}
	}
	{
		start := time.Now()
		err := a.server.Init(ctx)
		a.startupReport.Nodes = append(a.startupReport.Nodes, servo.StartupNode{Type: "*example.com/servovariants/api.Server", Duration: time.Since(start)})
		if err != nil {
			report := a.Shutdown(context.WithoutCancel(ctx))
			if report.Clean() {
				return nil, err
			}
			return nil, errors.Join(err, report)
		}
	}
	return a, nil
}

func (a *App) stopDb(ctx context.Context) servo.NodeResult {
	a.dbStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servovariants/postgres.DB", a.db.Stop))
		a.dbStopResult = servo.MergeNodeResults("*example.com/servovariants/postgres.DB", results...)
	})
	return a.dbStopResult
}

func (a *App) Run(ctx context.Context) error {
	return a.server.Run(ctx)
}

func (a *App) Shutdown(ctx context.Context) servo.Report {
	forceExit := make(chan os.Signal, 1)
	signal.Notify(forceExit, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(forceExit)
	watcherDone := make(chan struct{})
	defer close(watcherDone)
	go func() {
		select {
		case <-forceExit:
			os.Exit(1)
		case <-watcherDone:
		}
	}()

	var nodes []servo.NodeResult
	nodes = append(nodes, a.stopDb(ctx))
	return servo.Report{Nodes: nodes}
}

func (a *App) Health(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Ready(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Graph() servo.Graph {
	return servo.Graph{Nodes: []servo.GraphNode{
		{Type: "*example.com/servovariants/postgres.DB", Level: 1, Deps: nil, Capabilities: []string{"Initializer", "Finalizer"}, Binding: "explicit bind", Pos: "postgres/postgres.go:13:6"},
		{Type: "*example.com/servovariants/api.Server", Level: 2, Deps: []string{"*example.com/servovariants/postgres.DB"}, Capabilities: []string{"Initializer", "Runner"}, Binding: "sole candidate", Pos: "api/api.go:14:6"},
	}}
}

func (a *App) Report() servo.StartupReport {
	return a.startupReport
}
