//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// Resolved graph:
//
//	[L1] *example.com/servobasic/mockstore.Store
//	      deps: none
//	      capabilities: Finalizer | binding: explicit bind | mockstore/mockstore.go:29:6
//	[L2] *example.com/servobasic/api.Server
//	      deps: *example.com/servobasic/mockstore.Store
//	      capabilities: Runner, Drainer, Finalizer, Readier | binding: sole candidate | api/api.go:15:6
//	[L1] *example.com/servobasic/logger.Logger
//	      deps: none
//	      capabilities: Finalizer | binding: sole candidate | logger/logger.go:10:6
//	[L2] *example.com/servobasic/worker.Consumer
//	      deps: *example.com/servobasic/logger.Logger
//	      capabilities: Runner | binding: sole candidate | worker/worker.go:13:6
//	[L1] *example.com/servobasic/queue.OrdersAccount
//	      deps: none
//	      capabilities: none | binding: sole candidate | queue/queue.go:22:6
//	[L1] *example.com/servobasic/queue.AuditAccount
//	      deps: none
//	      capabilities: none | binding: sole candidate | queue/queue.go:26:6
//	[L2] *example.com/servobasic/relay.Relay
//	      deps: *example.com/servobasic/queue.OrdersAccount, *example.com/servobasic/queue.AuditAccount
//	      capabilities: Initializer | binding: sole candidate | relay/relay.go:24:6
package main

import (
	"context"
	"errors"
	"example.com/servobasic/api"
	"example.com/servobasic/logger"
	"example.com/servobasic/mockstore"
	"example.com/servobasic/queue"
	"example.com/servobasic/relay"
	"example.com/servobasic/worker"
	"github.com/okian/servo/v2/servo"
	"golang.org/x/sync/errgroup"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"
)

type TestApp struct {
	store            *mockstore.Store
	storeStopOnce    sync.Once
	storeStopResult  servo.NodeResult
	server           *api.Server
	serverStopOnce   sync.Once
	serverStopResult servo.NodeResult
	logger           *logger.Logger
	loggerStopOnce   sync.Once
	loggerStopResult servo.NodeResult
	consumer         *worker.Consumer
	ordersAccount    *queue.OrdersAccount
	auditAccount     *queue.AuditAccount
	relay            *relay.Relay
	startupReport    servo.StartupReport
}

func NewTestApp(ctx context.Context) (*TestApp, error) {
	a := &TestApp{}

	store := mockstore.New()
	a.store = store

	server := api.New(store)
	a.server = server

	logger := logger.New()
	a.logger = logger

	consumer := worker.New(logger)
	a.consumer = consumer

	ordersAccount := queue.NewOrdersAccount()
	a.ordersAccount = ordersAccount

	auditAccount := queue.NewAuditAccount()
	a.auditAccount = auditAccount

	relay := relay.New(ordersAccount, auditAccount)
	a.relay = relay

	{
		start := time.Now()
		err := a.relay.Init(ctx)
		a.startupReport.Nodes = append(a.startupReport.Nodes, servo.StartupNode{Type: "*example.com/servobasic/relay.Relay", Duration: time.Since(start)})
		if err != nil {
			report := a.Shutdown(ctx)
			return nil, errors.Join(err, report)
		}
	}
	return a, nil
}

func (a *TestApp) stopStore(ctx context.Context) servo.NodeResult {
	a.storeStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servobasic/mockstore.Store", a.store.Stop))
		a.storeStopResult = servo.MergeNodeResults("*example.com/servobasic/mockstore.Store", results...)
	})
	return a.storeStopResult
}

func (a *TestApp) stopServer(ctx context.Context) servo.NodeResult {
	a.serverStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servobasic/api.Server", a.server.Drain))
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servobasic/api.Server", a.server.Stop))
		a.serverStopResult = servo.MergeNodeResults("*example.com/servobasic/api.Server", results...)
	})
	return a.serverStopResult
}

func (a *TestApp) stopLogger(ctx context.Context) servo.NodeResult {
	a.loggerStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servobasic/logger.Logger", a.logger.Stop))
		a.loggerStopResult = servo.MergeNodeResults("*example.com/servobasic/logger.Logger", results...)
	})
	return a.loggerStopResult
}

func (a *TestApp) Run(ctx context.Context) error {
	g, gctx := errgroup.WithContext(ctx)
	g.Go(func() error { return a.server.Run(gctx) })
	g.Go(func() error { return a.consumer.Run(gctx) })
	return g.Wait()
}

func (a *TestApp) Shutdown(ctx context.Context) servo.Report {
	forceExit := make(chan os.Signal, 1)
	signal.Notify(forceExit, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(forceExit)
	watcherDone := make(chan struct{})
	defer close(watcherDone)
	go func() {
		select {
		case <-forceExit:
			os.Exit(1)
		case <-watcherDone:
		}
	}()

	var nodes []servo.NodeResult
	nodes = append(nodes, a.stopLogger(ctx))
	nodes = append(nodes, a.stopServer(ctx))
	nodes = append(nodes, a.stopStore(ctx))
	return servo.Report{Nodes: nodes}
}

func (a *TestApp) Health(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *TestApp) Ready(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	if err := a.server.Ready(ctx); err != nil {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servobasic/api.Server", Status: servo.StatusFailed, Err: err})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servobasic/api.Server", Status: servo.StatusOK})
	}
	return servo.Report{Nodes: nodes}
}

func (a *TestApp) Graph() servo.Graph {
	return servo.Graph{Nodes: []servo.GraphNode{
		{Type: "*example.com/servobasic/mockstore.Store", Level: 1, Deps: nil, Capabilities: []string{"Finalizer"}, Binding: "explicit bind", Pos: "mockstore/mockstore.go:29:6"},
		{Type: "*example.com/servobasic/api.Server", Level: 2, Deps: []string{"*example.com/servobasic/mockstore.Store"}, Capabilities: []string{"Runner", "Drainer", "Finalizer", "Readier"}, Binding: "sole candidate", Pos: "api/api.go:15:6"},
		{Type: "*example.com/servobasic/logger.Logger", Level: 1, Deps: nil, Capabilities: []string{"Finalizer"}, Binding: "sole candidate", Pos: "logger/logger.go:10:6"},
		{Type: "*example.com/servobasic/worker.Consumer", Level: 2, Deps: []string{"*example.com/servobasic/logger.Logger"}, Capabilities: []string{"Runner"}, Binding: "sole candidate", Pos: "worker/worker.go:13:6"},
		{Type: "*example.com/servobasic/queue.OrdersAccount", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "queue/queue.go:22:6"},
		{Type: "*example.com/servobasic/queue.AuditAccount", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "queue/queue.go:26:6"},
		{Type: "*example.com/servobasic/relay.Relay", Level: 2, Deps: []string{"*example.com/servobasic/queue.OrdersAccount", "*example.com/servobasic/queue.AuditAccount"}, Capabilities: []string{"Initializer"}, Binding: "sole candidate", Pos: "relay/relay.go:24:6"},
	}}
}

func (a *TestApp) Report() servo.StartupReport {
	return a.startupReport
}
