//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// ServoConfig fills Config from the process environment.
// Settings:
//
//	RATE_LIMIT_RPS float64, default 50
package resilience

import (
	"fmt"
	"os"
	"strconv"
)

// ServoConfig builds Config. Precedence per setting: default, then the RATE_LIMIT_* environment
// variable — the environment always wins.
func ServoConfig() (Config, error) {
	var cfg Config

	// rps — RATE_LIMIT_RPS
	cfg.RPS = 50
	if v, ok := os.LookupEnv("RATE_LIMIT_RPS"); ok {
		val, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return Config{}, fmt.Errorf("RATE_LIMIT_RPS: not a valid float64: %q", v)
		}
		cfg.RPS = val
	}
	return cfg, nil
}
