package emit

import (
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/tools/go/packages"

	"github.com/okian/servo/v3/internal/graph"
	"github.com/okian/servo/v3/internal/load"
	"github.com/okian/servo/v3/internal/resolve"
)

// loaderDecl is a hand-built ConfigDecl covering every kind family the
// loader emits differently: string, bool, sized int/uint, float, duration
// — required, defaulted, optional, and secret.
func loaderDecl() *graph.ConfigDecl {
	return &graph.ConfigDecl{
		Key:      graph.Key{Type: "example.com/app.settings"},
		TypeName: "settings",
		Prefix:   "APP",
		Section:  "app",
		PkgPath:  "example.com/app",
		PkgName:  "app",
		Dir:      "app",
		Pos:      token.Position{Filename: "app/settings.go", Line: 5},
		Fields: []graph.ConfigField{
			{FieldName: "dsn", Name: "dsn", EnvName: "APP_DSN", FileKey: "dsn", Kind: graph.KindString, Required: true},
			{FieldName: "maxConns", Name: "max_conns", EnvName: "APP_MAX_CONNS", FileKey: "max_conns", Kind: graph.KindInt32, HasDefault: true, Default: "10"},
			{FieldName: "connLifetime", Name: "conn_lifetime", EnvName: "APP_CONN_LIFETIME", FileKey: "conn_lifetime", Kind: graph.KindDuration, HasDefault: true, Default: "30m", DefaultDuration: 30 * 60 * 1e9},
			{FieldName: "verbose", Name: "verbose", EnvName: "APP_VERBOSE", FileKey: "verbose", Kind: graph.KindBool},
			{FieldName: "token", Name: "token", EnvName: "APP_TOKEN", FileKey: "token", Kind: graph.KindString, Required: true, Secret: true},
			{FieldName: "rate", Name: "rate", EnvName: "APP_RATE", FileKey: "rate", Kind: graph.KindFloat64, HasDefault: true, Default: "1.5"},
			{FieldName: "retries", Name: "retries", EnvName: "APP_RETRIES", FileKey: "retries", Kind: graph.KindUint8, HasDefault: true, Default: "3"},
			// A secret non-string field reaches the errors.New redaction
			// path, which is the one that must never echo the value.
			{FieldName: "burst", Name: "burst", EnvName: "APP_BURST", FileKey: "burst", Kind: graph.KindInt64, Secret: true},
		},
	}
}

// loaderStructSrc mirrors loaderDecl as source, so the emitted loader can
// be type-checked against the struct it fills.
const loaderStructSrc = `
package app

import "time"

type settings struct {
	dsn          string
	maxConns     int32
	connLifetime time.Duration
	verbose      bool
	token        string
	rate         float64
	retries      uint8
	burst        int64
}

// keep the fields referenced so the fixture itself is vet-clean
var _ = settings{}.dsn
var _ = settings{}.token
`

func checkGolden(t *testing.T, name string, out []byte) {
	t.Helper()
	goldenPath := filepath.Join("testdata", "golden", name)
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(goldenPath, out, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Skip("golden file updated")
	}
	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden (run with UPDATE_GOLDEN=1 to create it): %v", err)
	}
	if string(out) != string(want) {
		t.Errorf("output does not match golden file %s (run with UPDATE_GOLDEN=1 to review+accept changes)\n--- got ---\n%s", goldenPath, out)
	}
}

// typecheckLoader compiles the emitted loader together with the struct it
// fills — the strongest promise a unit test can make about generated code,
// since `servo generate` itself only formats it.
func typecheckLoader(t *testing.T, loader []byte, extraPkgs ...string) {
	t.Helper()
	fset := token.NewFileSet()
	structFile, err := parser.ParseFile(fset, "settings.go", loaderStructSrc, 0)
	if err != nil {
		t.Fatalf("parse struct fixture: %v", err)
	}
	loaderFile, err := parser.ParseFile(fset, ConfigLoaderFileName, string(loader), 0)
	if err != nil {
		t.Fatalf("parse emitted loader: %v", err)
	}
	deps := []string{"os", "fmt", "errors", "strconv", "strings", "time"}
	roots := loadPackages(t, append(deps, extraPkgs...))
	conf := types.Config{Importer: newPkgImporter(roots...)}
	if _, err := conf.Check("example.com/app", fset, []*ast.File{structFile, loaderFile}, nil); err != nil {
		t.Fatalf("emitted loader does not type-check: %v\n---\n%s", err, loader)
	}
}

func TestEmitConfigLoaderEnvOnly(t *testing.T) {
	out, err := EmitConfigLoader(loaderDecl(), false)
	if err != nil {
		t.Fatalf("EmitConfigLoader: %v", err)
	}
	src := string(out)

	for _, want := range []string{
		"//go:build !servoinject",
		"// Code generated by servo generate. DO NOT EDIT.",
		"func ServoConfig() (settings, error) {",
		`if v, ok := os.LookupEnv("APP_DSN"); ok {`,
		"missing = append(missing, \"APP_DSN\")",
		"cfg.maxConns = 10",
		"strconv.ParseInt(v, 10, 32)",
		"cfg.maxConns = int32(val)",
		"cfg.connLifetime = 30 * time.Minute",
		"time.ParseDuration(v)",
		"strconv.ParseBool(v)",
		"cfg.rate = 1.5",
		"strconv.ParseUint(v, 10, 8)",
		"cfg.retries = uint8(val)",
		// The secret parse failure names the variable and the type, never
		// the value.
		`errors.New("APP_BURST: not a valid int64 (value redacted: secret)")`,
		`fmt.Errorf("app: missing required configuration: %s", strings.Join(missing, ", "))`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("loader missing %q\n---\n%s", want, src)
		}
	}
	if strings.Contains(src, "conf.") || strings.Contains(src, "map[string]any") {
		t.Errorf("env-only loader must not carry file machinery\n---\n%s", src)
	}
	// A non-secret parse error echoes the value; the secret one must not.
	if !strings.Contains(src, `fmt.Errorf("APP_MAX_CONNS: not a valid int32: %q", v)`) {
		t.Errorf("non-secret parse error should name the value\n---\n%s", src)
	}

	typecheckLoader(t, out)
	checkGolden(t, "configloader_env.go.golden", out)
}

func TestEmitConfigLoaderWithFile(t *testing.T) {
	out, err := EmitConfigLoader(loaderDecl(), true)
	if err != nil {
		t.Fatalf("EmitConfigLoader: %v", err)
	}
	src := string(out)

	for _, want := range []string{
		"func ServoConfig(file map[string]any) (settings, error) {",
		`section, err := conf.Section(file, "app")`,
		`if v, ok := section["max_conns"]; ok {`,
		"conf.Int32(v)",
		"conf.Duration(v)",
		// Required + two sources: tracked with a set flag, and the missing
		// message names both spellings.
		"dsnSet := false",
		`missing = append(missing, "APP_DSN (env) or app.dsn (config file)")`,
		// Env still wins: the env read comes after the section read.
		`if v, ok := os.LookupEnv("APP_DSN"); ok {`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("loader missing %q\n---\n%s", want, src)
		}
	}
	if fileIdx, envIdx := strings.Index(src, `section["dsn"]`), strings.Index(src, `os.LookupEnv("APP_DSN")`); fileIdx == -1 || envIdx < fileIdx {
		t.Errorf("environment must be read after the file section so it wins")
	}

	typecheckLoader(t, out, confPackagePath)
	checkGolden(t, "configloader_file.go.golden", out)
}

// loadPackages loads several dependency packages in one go/packages call,
// so type-checking emitted code shares object identity with them.
func loadPackages(t *testing.T, paths []string) []*packages.Package {
	t.Helper()
	cfg := &packages.Config{Mode: packages.NeedName | packages.NeedTypes | packages.NeedDeps | packages.NeedImports}
	pkgs, err := packages.Load(cfg, paths...)
	if err != nil {
		t.Fatalf("load %v: %v", paths, err)
	}
	return pkgs
}

// configEmitSrc is the injector-side fixture: an unexported config type
// consumed by the root, in the injector's own package.
const configEmitSrc = `
package app

type settings struct {
	dsn string
}

type Server struct{}
func NewServer(s settings) *Server { return &Server{} }

var _ = settings{}.dsn
`

func buildConfigResolved(t *testing.T, configFile *load.ConfigFileDecl) (*resolve.Resolved, *load.Spec) {
	t.Helper()
	servoPkg := loadServoPackage(t)
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "app.go", configEmitSrc, 0)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	conf := types.Config{Importer: newPkgImporter(servoPkg)}
	pkg, err := conf.Check("example.com/app", fset, []*ast.File{f}, nil)
	if err != nil {
		t.Fatalf("typecheck: %v", err)
	}
	pkgsPkg := &packages.Package{Name: "app", PkgPath: "example.com/app", Types: pkg, Fset: fset}
	candidates, _ := graph.ScanCandidates([]*packages.Package{pkgsPkg}, "example.com/app")

	settingsType := pkg.Scope().Lookup("settings").Type()
	decl := &graph.ConfigDecl{
		Key:      graph.NewKey(settingsType, ""),
		Type:     settingsType,
		TypeName: "settings",
		Prefix:   "APP",
		Section:  "app",
		PkgPath:  "example.com/app",
		PkgName:  "app",
		Dir:      "app",
		Pos:      token.Position{Filename: "app.go", Line: 3},
		Fields: []graph.ConfigField{
			{FieldName: "dsn", Name: "dsn", EnvName: "APP_DSN", FileKey: "dsn", Kind: graph.KindString, Required: true, Pos: token.Position{Filename: "app.go", Line: 4}},
		},
	}

	serverType := types.NewPointer(pkg.Scope().Lookup("Server").Type())
	spec := &load.Spec{
		InjectorPkg: pkgsPkg,
		Roots:       []load.RootDecl{{Key: graph.NewKey(serverType, ""), Type: serverType, Pos: token.Position{Filename: "spec.go", Line: 9}}},
		ConfigFile:  configFile,
	}
	resolved, diags := resolve.Resolve(resolve.Input{
		Spec:       spec,
		Candidates: candidates,
		Caps:       graph.EmptyCapabilities(),
		Scope:      map[string]bool{"example.com/app": true},
		Configs:    []*graph.ConfigDecl{decl},
	})
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	return resolved, spec
}

func TestEmitInjectorWithEnvOnlyConfig(t *testing.T) {
	resolved, spec := buildConfigResolved(t, nil)
	out, err := Emit(resolved, spec, false)
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}
	src := string(out)

	for _, want := range []string{
		// Loaded in the preamble, bare-named (config lives in the
		// injector's own package), held as a local — never an App field.
		"settings, err := ServoConfig()",
		"server := NewServer(settings)",
		// The graph header and Graph() carry it at level 0 (gofmt renders
		// the header block tab-indented).
		"//\t[L0] example.com/app.settings",
		"servo:config (prefix APP)",
		`{Type: "example.com/app.settings", Level: 0, Deps: nil, Capabilities: nil, Binding: "config directive", Pos: "app.go:3"},`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q\n---\n%s", want, src)
		}
	}
	for _, reject := range []string{
		"a.settings",          // no App field: the type may be unexported to its package
		"servoLoadConfigFile", // env-only: no file machinery
		"configFile",
	} {
		if strings.Contains(src, reject) {
			t.Errorf("generated source must not contain %q\n---\n%s", reject, src)
		}
	}
}

func TestEmitInjectorWithJSONConfigFile(t *testing.T) {
	resolved, spec := buildConfigResolved(t, &load.ConfigFileDecl{Path: "config.json", Pos: token.Position{Filename: "spec.go", Line: 10}})
	out, err := Emit(resolved, spec, false)
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}
	src := string(out)

	for _, want := range []string{
		"configFile, err := servoLoadConfigFile()",
		"settings, err := ServoConfig(configFile)",
		"func servoLoadConfigFile() (map[string]any, error) {",
		`path, explicit := "config.json", false`,
		`if v, ok := os.LookupEnv("CONFIG_FILE"); ok {`,
		"switch filepath.Ext(path) {",
		`case ".json":`,
		"json.Unmarshal(data, &file)",
		// The default path may be absent (env still serves everything); an
		// explicitly set path may not.
		"if os.IsNotExist(err) && !explicit {",
		`"encoding/json"`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q\n---\n%s", want, src)
		}
	}
	for _, reject := range []string{"yaml", "toml"} {
		if strings.Contains(src, reject) {
			t.Errorf("a json injector must not carry a %s decoder\n---\n%s", reject, src)
		}
	}
}

func TestEmitInjectorConfigDecoderPerExtension(t *testing.T) {
	cases := []struct{ path, importLine, wantExts string }{
		{"config.yaml", `yaml "gopkg.in/yaml.v3"`, `case ".yaml", ".yml":`},
		{"config.toml", `toml "github.com/BurntSushi/toml"`, `case ".toml":`},
	}
	for _, tc := range cases {
		resolved, spec := buildConfigResolved(t, &load.ConfigFileDecl{Path: tc.path, Pos: token.Position{Filename: "spec.go", Line: 10}})
		out, err := Emit(resolved, spec, false)
		if err != nil {
			t.Fatalf("Emit(%s): %v", tc.path, err)
		}
		src := string(out)
		if !strings.Contains(src, tc.importLine) && !strings.Contains(src, strings.Fields(tc.importLine)[1]) {
			t.Errorf("%s: missing decoder import %q\n---\n%s", tc.path, tc.importLine, src)
		}
		if !strings.Contains(src, tc.wantExts) {
			t.Errorf("%s: missing extension gate %q", tc.path, tc.wantExts)
		}
	}
}

// TestEmitInjectorTestModeConfig pins the override variant's loader name:
// servo_gen_test.go lands in the same package as servo_gen.go, so its
// file-reading helper needs the test prefix the scope types already use.
func TestEmitInjectorTestModeConfig(t *testing.T) {
	resolved, spec := buildConfigResolved(t, &load.ConfigFileDecl{Path: "config.json", Pos: token.Position{Filename: "spec.go", Line: 10}})
	out, err := Emit(resolved, spec, true)
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}
	src := string(out)
	if !strings.Contains(src, "func testServoLoadConfigFile() (map[string]any, error)") {
		t.Errorf("test variant should emit a test-prefixed loader\n---\n%s", src)
	}
	if strings.Contains(src, "func servoLoadConfigFile()") {
		t.Errorf("test variant must not redeclare the production loader\n---\n%s", src)
	}
}
