package emit

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/okian/servo/v3/internal/graph"
)

// ConfigLoaderFileName is the companion file EmitConfigLoader's output is
// written to, in the config type's own package directory. It carries the
// !servoinject constraint, so — exactly like the injector's own generated
// file — generation never sees the previous run's output.
const ConfigLoaderFileName = "servo_config_gen.go"

// ConfigLoaderFuncName is the one exported identifier a //servo:config
// package gains: the generated loader the injector calls. Everything else
// about the config — the type, its fields, its tags — can stay unexported,
// because this file lives in the same package; the export exists only
// because the injector lives in another one and Go has no narrower door.
const ConfigLoaderFuncName = "ServoConfig"

// confPackagePath is the stdlib-only coercion runtime generated file-value
// code calls. Only emitted (and therefore only a dependency) when the
// injector declares a servo.ConfigFile.
const confPackagePath = "github.com/okian/servo/v3/conf"

// EmitConfigLoader renders the companion file for one //servo:config type:
// plain, steppable parsing — defaults, then the config-file section when
// withFile is set, then the environment, which always wins — with every
// missing required setting collected into one error that names each
// variable an operator has to set.
//
// withFile decides the loader's signature: ServoConfig(file map[string]any)
// when the module's injectors declare a servo.ConfigFile, ServoConfig()
// when they are env-only. It is a property of the module, not of one
// injector — a shared companion cannot have two signatures — and the
// caller (cmd/servo) enforces that agreement before emitting anything.
func EmitConfigLoader(decl *graph.ConfigDecl, withFile bool) ([]byte, error) {
	var body strings.Builder
	writeConfigHeader(&body, decl, withFile)
	fmt.Fprintf(&body, "package %s\n\n", decl.PkgName)
	body.WriteString(configImports(decl, withFile))
	writeConfigFunc(&body, decl, withFile)

	formatted, err := format.Source([]byte(body.String()))
	if err != nil {
		return nil, fmt.Errorf("emit: generated config loader failed to format (this is a servo bug, not a user error):\n%w\n---\n%s", err, body.String())
	}
	return formatted, nil
}

// writeConfigHeader documents the settings this loader reads — the file is
// the reference an operator greps when a deploy is missing a variable, so
// the header is the table, not prose.
func writeConfigHeader(b *strings.Builder, decl *graph.ConfigDecl, withFile bool) {
	b.WriteString("//go:build !servoinject\n\n")
	b.WriteString("// Code generated by servo generate. DO NOT EDIT.\n//\n")
	fmt.Fprintf(b, "// %s fills %s from", ConfigLoaderFuncName, decl.TypeName)
	if withFile {
		fmt.Fprintf(b, " the config file section %q and", decl.Section)
	}
	b.WriteString(" the process environment.\n")
	b.WriteString("// Settings:\n")
	for _, f := range decl.Fields {
		attrs := []string{f.Kind.GoType()}
		switch {
		case f.Required:
			attrs = append(attrs, "required")
		case f.HasDefault:
			attrs = append(attrs, "default "+f.Default)
		}
		if f.Secret {
			attrs = append(attrs, "secret")
		}
		fmt.Fprintf(b, "//   %-*s %s\n", configEnvWidth(decl), f.EnvName, strings.Join(attrs, ", "))
	}
	b.WriteString("//\n")
}

func configEnvWidth(decl *graph.ConfigDecl) int {
	w := 0
	for _, f := range decl.Fields {
		if len(f.EnvName) > w {
			w = len(f.EnvName)
		}
	}
	return w
}

// configImports computes the exact import block: a loader for a struct of
// optional strings imports nothing but os, and only a file-reading one
// carries the conf runtime.
func configImports(decl *graph.ConfigDecl, withFile bool) string {
	std := map[string]bool{"os": true}
	for _, f := range decl.Fields {
		if f.Required {
			std["fmt"] = true
			std["strings"] = true
		}
		switch f.Kind {
		case graph.KindString:
			// no parsing
		case graph.KindDuration:
			std["time"] = true
			std["fmt"] = true
		default:
			std["strconv"] = true
			std["fmt"] = true
		}
		if f.Kind != graph.KindString && f.Secret {
			std["errors"] = true
		}
		if f.HasDefault && f.Kind == graph.KindDuration && f.DefaultDuration != 0 {
			std["time"] = true
		}
	}
	if withFile {
		std["fmt"] = true
	}

	paths := make([]string, 0, len(std))
	for p := range std {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString("import (\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "\t%q\n", p)
	}
	if withFile {
		b.WriteString("\n")
		fmt.Fprintf(&b, "\t%q\n", confPackagePath)
	}
	b.WriteString(")\n\n")
	return b.String()
}

func writeConfigFunc(b *strings.Builder, decl *graph.ConfigDecl, withFile bool) {
	fmt.Fprintf(b, "// %s builds %s. Precedence per setting: default", ConfigLoaderFuncName, decl.TypeName)
	if withFile {
		fmt.Fprintf(b, ",\n// then the config file's %q section", decl.Section)
	}
	fmt.Fprintf(b, ", then the %s_* environment\n// variable — the environment always wins.\n", decl.Prefix)
	if withFile {
		fmt.Fprintf(b, "func %s(file map[string]any) (%s, error) {\n", ConfigLoaderFuncName, decl.TypeName)
	} else {
		fmt.Fprintf(b, "func %s() (%s, error) {\n", ConfigLoaderFuncName, decl.TypeName)
	}
	fmt.Fprintf(b, "\tvar cfg %s\n", decl.TypeName)
	if anyRequired(decl) {
		b.WriteString("\tvar missing []string\n")
	}
	if withFile {
		fmt.Fprintf(b, "\n\tsection, err := conf.Section(file, %q)\n", decl.Section)
		fmt.Fprintf(b, "\tif err != nil {\n\t\treturn %s{}, err\n\t}\n", decl.TypeName)
	}

	for _, f := range decl.Fields {
		b.WriteString("\n")
		writeConfigField(b, decl, f, withFile)
	}

	if anyRequired(decl) {
		b.WriteString("\n\tif len(missing) > 0 {\n")
		fmt.Fprintf(b, "\t\treturn %s{}, fmt.Errorf(\"%s: missing required configuration: %%s\", strings.Join(missing, \", \"))\n", decl.TypeName, decl.PkgName)
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn cfg, nil\n}\n")
}

func anyRequired(decl *graph.ConfigDecl) bool {
	for _, f := range decl.Fields {
		if f.Required {
			return true
		}
	}
	return false
}

func writeConfigField(b *strings.Builder, decl *graph.ConfigDecl, f graph.ConfigField, withFile bool) {
	fileKey := decl.Section + "." + f.FileKey
	fmt.Fprintf(b, "\t// %s — %s", f.Name, f.EnvName)
	if withFile {
		fmt.Fprintf(b, " / %s", fileKey)
	}
	if f.Required {
		b.WriteString(" (required)")
	}
	b.WriteString("\n")

	if f.HasDefault {
		fmt.Fprintf(b, "\tcfg.%s = %s\n", f.FieldName, configDefaultLiteral(f))
	}
	setVar := f.FieldName + "Set"
	// The <field>Set tracker exists only where both sources can satisfy a
	// required field; env-only required fields use a plain else instead.
	trackSet := f.Required && withFile
	if trackSet {
		fmt.Fprintf(b, "\t%s := false\n", setVar)
	}

	if withFile {
		fmt.Fprintf(b, "\tif v, ok := section[%q]; ok {\n", f.FileKey)
		fmt.Fprintf(b, "\t\tval, err := conf.%s(v)\n", confHelperName(f.Kind))
		fmt.Fprintf(b, "\t\tif err != nil {\n\t\t\treturn %s{}, fmt.Errorf(\"%s (config file): %%w\", err)\n\t\t}\n", decl.TypeName, fileKey)
		fmt.Fprintf(b, "\t\tcfg.%s = val\n", f.FieldName)
		if trackSet {
			fmt.Fprintf(b, "\t\t%s = true\n", setVar)
		}
		b.WriteString("\t}\n")
	}

	fmt.Fprintf(b, "\tif v, ok := os.LookupEnv(%q); ok {\n", f.EnvName)
	writeEnvParse(b, decl, f)
	if trackSet {
		fmt.Fprintf(b, "\t\t%s = true\n", setVar)
	}
	if f.Required && !withFile {
		b.WriteString("\t} else {\n")
		fmt.Fprintf(b, "\t\tmissing = append(missing, %q)\n", f.EnvName)
	}
	b.WriteString("\t}\n")
	if trackSet {
		fmt.Fprintf(b, "\tif !%s {\n", setVar)
		fmt.Fprintf(b, "\t\tmissing = append(missing, %q)\n", f.EnvName+" (env) or "+fileKey+" (config file)")
		b.WriteString("\t}\n")
	}
}

// writeEnvParse converts the raw environment string v into the field's own
// type: a strconv or time call the reader can step through, with an error
// that names the variable — and, for a field tagged secret, never echoes
// the value that failed to parse.
func writeEnvParse(b *strings.Builder, decl *graph.ConfigDecl, f graph.ConfigField) {
	assignCast := func(expr string) {
		fmt.Fprintf(b, "\t\tval, err := %s\n", expr)
		b.WriteString("\t\tif err != nil {\n")
		writeEnvParseError(b, decl, f)
		b.WriteString("\t\t}\n")
		if cast := envCast(f.Kind); cast != "" {
			fmt.Fprintf(b, "\t\tcfg.%s = %s(val)\n", f.FieldName, cast)
		} else {
			fmt.Fprintf(b, "\t\tcfg.%s = val\n", f.FieldName)
		}
	}

	switch f.Kind {
	case graph.KindString:
		fmt.Fprintf(b, "\t\tcfg.%s = v\n", f.FieldName)
	case graph.KindBool:
		assignCast("strconv.ParseBool(v)")
	case graph.KindInt, graph.KindInt8, graph.KindInt16, graph.KindInt32, graph.KindInt64:
		assignCast(fmt.Sprintf("strconv.ParseInt(v, 10, %d)", f.Kind.StrconvBits()))
	case graph.KindUint, graph.KindUint8, graph.KindUint16, graph.KindUint32, graph.KindUint64:
		assignCast(fmt.Sprintf("strconv.ParseUint(v, 10, %d)", f.Kind.StrconvBits()))
	case graph.KindFloat32, graph.KindFloat64:
		assignCast(fmt.Sprintf("strconv.ParseFloat(v, %d)", f.Kind.StrconvBits()))
	case graph.KindDuration:
		assignCast("time.ParseDuration(v)")
	}
}

func writeEnvParseError(b *strings.Builder, decl *graph.ConfigDecl, f graph.ConfigField) {
	if f.Secret {
		fmt.Fprintf(b, "\t\t\treturn %s{}, errors.New(\"%s: not a valid %s (value redacted: secret)\")\n", decl.TypeName, f.EnvName, f.Kind.GoType())
		return
	}
	fmt.Fprintf(b, "\t\t\treturn %s{}, fmt.Errorf(\"%s: not a valid %s: %%q\", v)\n", decl.TypeName, f.EnvName, f.Kind.GoType())
}

// envCast is the conversion from strconv's widest result down to the
// field's own type; "" where the parse already lands on it.
func envCast(k graph.ConfigKind) string {
	switch k {
	case graph.KindInt64, graph.KindUint64, graph.KindFloat64, graph.KindString, graph.KindBool, graph.KindDuration:
		return ""
	default:
		return k.GoType()
	}
}

// confHelperName is the conf package coercion the file path calls for a
// kind: conf.Int32, conf.Duration, ...
func confHelperName(k graph.ConfigKind) string {
	if k == graph.KindDuration {
		return "Duration"
	}
	return capitalize(k.GoType())
}

// configDefaultLiteral renders a validated default as source: quoted for
// strings, a readable duration expression for durations, verbatim for the
// numeric and bool kinds (scan already parsed them, so they are known
// well-formed literals).
func configDefaultLiteral(f graph.ConfigField) string {
	switch f.Kind {
	case graph.KindString:
		return fmt.Sprintf("%q", f.Default)
	case graph.KindDuration:
		return durationLiteral(f.DefaultDuration)
	default:
		return f.Default
	}
}
