// Package emit turns a resolved graph into a single, deterministic,
// gofmt-clean Go source file: construction, phased lifecycle, supervision,
// and static graph introspection data.
package emit

import (
	"fmt"
	"go/format"
	"go/token"
	"go/types"
	"path/filepath"
	"sort"
	"strings"

	"github.com/okian/servo/v3/internal/graph"
	"github.com/okian/servo/v3/internal/load"
	"github.com/okian/servo/v3/internal/resolve"
)

type emitter struct {
	resolved *resolve.Resolved
	spec     *load.Spec
	pkgName  string
	testMode bool // NewTestApp instead of New (servotest override variant)

	imports    *ImportManager
	names      *NameAllocator
	varName    map[graph.Key]string
	servoAlias string
}

// Emit renders the full generated file for resolved. When testMode is true,
// the constructor is named NewTestApp (the servotest override variant)
// instead of New.
func Emit(resolved *resolve.Resolved, spec *load.Spec, testMode bool) ([]byte, error) {
	e := &emitter{
		resolved: resolved,
		spec:     spec,
		pkgName:  spec.InjectorPkg.Name,
		testMode: testMode,
		imports:  NewImportManager(),
		names:    NewNameAllocator(),
		varName:  map[graph.Key]string{},
	}
	e.servoAlias = e.imports.Add(graph.ServoPackagePath, "servo")
	e.imports.Add("context", "context")

	for _, n := range resolved.Order {
		e.varName[n.Key] = e.names.Allocate(n.Provider.ResultType)
	}

	appStruct := e.appStruct()
	newFunc := e.newFunc()
	stopMethods := e.stopMethods()
	runFunc := e.runFunc()
	shutdownFunc := e.shutdownFunc()
	healthFunc := e.healthReadyFunc("Health", "Healther", "Health")
	readyFunc := e.healthReadyFunc("Ready", "Readier", "Ready")
	graphFunc := e.graphFunc()
	reportFunc := e.reportFunc()

	var body strings.Builder
	body.WriteString(e.header())
	fmt.Fprintf(&body, "package %s\n\n", e.pkgName)
	body.WriteString(e.imports.RenderImports())
	body.WriteString("\n")
	body.WriteString(appStruct)
	body.WriteString(newFunc)
	body.WriteString(stopMethods)
	body.WriteString(runFunc)
	body.WriteString(shutdownFunc)
	body.WriteString(healthFunc)
	body.WriteString(readyFunc)
	body.WriteString(graphFunc)
	body.WriteString(reportFunc)

	formatted, err := format.Source([]byte(body.String()))
	if err != nil {
		return nil, fmt.Errorf("emit: generated source failed to format (this is a servo bug, not a user error):\n%w\n---\n%s", err, body.String())
	}
	return formatted, nil
}

// header documents the resolved graph: every node, its level, dependencies,
// detected capabilities, and how its provider was selected.
func (e *emitter) header() string {
	var b strings.Builder
	b.WriteString("//go:build !servoinject\n\n")
	b.WriteString("// Code generated by servo generate. DO NOT EDIT.\n//\n// Resolved graph:\n")
	for _, n := range e.resolved.Order {
		deps := "none"
		if len(n.Deps) > 0 {
			names := make([]string, len(n.Deps))
			for i, d := range n.Deps {
				names[i] = d.Key.String()
			}
			deps = strings.Join(names, ", ")
		}
		caps := "none"
		if len(n.Capabilities) > 0 {
			caps = strings.Join(n.Capabilities, ", ")
		}
		fmt.Fprintf(&b, "//   [L%d] %s\n//         deps: %s\n//         capabilities: %s | binding: %s | %s\n",
			n.Level, n.Key.String(), deps, caps, n.Binding, e.posString(n.Provider.Pos))
	}
	b.WriteString("//\n")
	return b.String()
}

// posString renders pos relative to the injector's module root when
// possible, so the generated file is byte-identical across checkouts at
// different absolute paths rather than embedding one machine's filesystem
// layout in a file meant to be committed to VCS.
func (e *emitter) posString(pos token.Position) string {
	if mod := e.spec.InjectorPkg.Module; mod != nil && mod.Dir != "" {
		if rel, err := filepath.Rel(mod.Dir, pos.Filename); err == nil && !strings.HasPrefix(rel, "..") {
			pos.Filename = filepath.ToSlash(rel)
		}
	}
	return pos.String()
}

func (e *emitter) constructorName() string {
	if e.testMode {
		return "NewTestApp"
	}
	return "New"
}

// appType names the generated container struct. The test-override variant
// can resolve entirely different concrete types for the same interface keys
// — different fields, different capabilities, a different set of stop
// methods — so it cannot share the App struct with production code; it
// gets its own TestApp in a separate _test.go file instead.
func (e *emitter) appType() string {
	if e.testMode {
		return "TestApp"
	}
	return "App"
}

func (e *emitter) appStruct() string {
	var b strings.Builder
	fmt.Fprintf(&b, "type %s struct {\n", e.appType())
	for _, n := range e.resolved.Order {
		name := e.varName[n.Key]
		fmt.Fprintf(&b, "\t%s %s\n", name, e.qualifiedTypeString(n.Provider.ResultType))
		if n.Provider.HasCleanup {
			fmt.Fprintf(&b, "\t%sCleanup func()\n", name)
		}
		if e.needsStopMethod(n) {
			e.imports.Add("sync", "sync")
			fmt.Fprintf(&b, "\t%sStopOnce sync.Once\n", name)
			fmt.Fprintf(&b, "\t%sStopResult %s.NodeResult\n", name, e.servoAlias)
		}
	}
	fmt.Fprintf(&b, "\tstartupReport %s.StartupReport\n", e.servoAlias)
	b.WriteString("}\n\n")
	return b.String()
}

func (e *emitter) needsStopMethod(n *resolve.Node) bool {
	if n.Provider.HasCleanup {
		return true
	}
	return hasCapability(n, "Drainer") || hasCapability(n, "Flusher") || hasCapability(n, "Finalizer")
}

func hasCapability(n *resolve.Node, name string) bool {
	for _, c := range n.Capabilities {
		if c == name {
			return true
		}
	}
	return false
}

// qualifiedTypeString renders t as it should appear in generated source,
// registering whatever import it needs along the way.
func (e *emitter) qualifiedTypeString(t types.Type) string {
	switch u := types.Unalias(t).(type) {
	case *types.Pointer:
		return "*" + e.qualifiedTypeString(u.Elem())
	case *types.Named:
		obj := u.Obj()
		name := obj.Name()
		if obj.Pkg() != nil {
			if ident := e.pkgIdent(obj.Pkg()); ident != "" {
				name = ident + "." + name
			}
		}
		// An instantiated generic type must carry its type arguments:
		// Cache[string] rendered as a bare "Cache" is the uninstantiated
		// generic, which is not a usable type ("cannot use generic type
		// without instantiation"). Arguments recurse so they get qualified
		// and imported the same way the outer type does.
		if targs := u.TypeArgs(); targs != nil && targs.Len() > 0 {
			args := make([]string, targs.Len())
			for i := range args {
				args[i] = e.qualifiedTypeString(targs.At(i))
			}
			name += "[" + strings.Join(args, ", ") + "]"
		}
		return name
	case *types.Interface:
		if u.NumMethods() == 0 {
			return "any"
		}
		return types.TypeString(u, e.qualifierFunc())
	default:
		return types.TypeString(u, e.qualifierFunc())
	}
}

// pkgIdent returns the identifier to qualify a reference to pkg with, or ""
// when pkg is the injector's own package: the generated file lives in that
// package, so referencing it via a bare name is required, not just
// permitted — importing your own package is a compile error.
func (e *emitter) pkgIdent(pkg *types.Package) string {
	if pkg.Path() == e.spec.InjectorPkg.PkgPath {
		return ""
	}
	return e.imports.Add(pkg.Path(), pkg.Name())
}

func (e *emitter) qualifierFunc() types.Qualifier {
	return func(p *types.Package) string { return e.pkgIdent(p) }
}

// qualifiedFuncString renders a provider's function reference: bare within
// the injector's own package (self-import is illegal), qualified otherwise.
func (e *emitter) qualifiedFuncString(p *graph.Provider) string {
	if ident := e.pkgIdent(p.Func.Pkg()); ident != "" {
		return ident + "." + p.Func.Name()
	}
	return p.Func.Name()
}

func stringSliceLiteral(ss []string) string {
	if len(ss) == 0 {
		return "nil"
	}
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

// levelGroups groups nodes satisfying pred by Level, ascending, preserving
// each level's relative (DFS post-order) sequence.
func levelGroups(nodes []*resolve.Node, pred func(*resolve.Node) bool) [][]*resolve.Node {
	byLevel := map[int][]*resolve.Node{}
	var levels []int
	for _, n := range nodes {
		if !pred(n) {
			continue
		}
		if _, ok := byLevel[n.Level]; !ok {
			levels = append(levels, n.Level)
		}
		byLevel[n.Level] = append(byLevel[n.Level], n)
	}
	sort.Ints(levels)
	groups := make([][]*resolve.Node, len(levels))
	for i, lvl := range levels {
		groups[i] = byLevel[lvl]
	}
	return groups
}
