//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// ServoConfig fills ListenConfig from the process environment.
// Settings:
//
//	HTTP_ADDR string, default :8080
package servoapi

import (
	"os"
)

// ServoConfig builds ListenConfig. Precedence per setting: default, then the HTTP_* environment
// variable — the environment always wins.
func ServoConfig() (ListenConfig, error) {
	var cfg ListenConfig

	// addr — HTTP_ADDR
	cfg.Addr = ":8080"
	if v, ok := os.LookupEnv("HTTP_ADDR"); ok {
		cfg.Addr = v
	}
	return cfg, nil
}
