//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// Resolved graph:
//
//	[L1] *example.com/servoorders/internal/config.Env
//	      deps: none
//	      capabilities: none | binding: sole implementation | internal/config/config.go:42:6
//	[L2] *example.com/servoorders/internal/session.Config
//	      deps: *example.com/servoorders/internal/config.Env
//	      capabilities: none | binding: sole candidate | internal/session/session.go:66:6
//	[L2] *example.com/servoorders/internal/observability.Config
//	      deps: *example.com/servoorders/internal/config.Env
//	      capabilities: none | binding: sole candidate | internal/observability/logging.go:21:6
//	[L3] *example.com/servoorders/internal/observability.Logger
//	      deps: *example.com/servoorders/internal/observability.Config
//	      capabilities: none | binding: sole candidate | internal/observability/logging.go:35:6
//	[L2] *github.com/okian/servo/v3/servo.HTTPConfig
//	      deps: *example.com/servoorders/internal/config.Env
//	      capabilities: none | binding: sole candidate | internal/transport/servoapi/middleware.go:88:6
//	[L1] *example.com/servoorders/internal/transport/servoapi.ClaimsExtractor
//	      deps: none
//	      capabilities: none | binding: sole candidate | internal/transport/servoapi/middleware.go:69:6
//	[L1] *github.com/okian/servo/v3/middleware.Recover
//	      deps: none
//	      capabilities: none | binding: sole candidate | /Users/kian/servo/middleware/recover.go:17:6
//	[L2] *example.com/servoorders/internal/resilience.Config
//	      deps: *example.com/servoorders/internal/config.Env
//	      capabilities: none | binding: sole candidate | internal/resilience/ratelimit.go:29:6
//	[L1] *example.com/servoorders/internal/observability.Metrics
//	      deps: none
//	      capabilities: none | binding: sole candidate | internal/observability/metrics.go:18:6
//	[L3] *example.com/servoorders/internal/resilience.RateLimiter
//	      deps: *example.com/servoorders/internal/resilience.Config, *example.com/servoorders/internal/observability.Metrics
//	      capabilities: none | binding: sole candidate | internal/resilience/ratelimit.go:33:6
//	[L3] *example.com/servoorders/internal/observability.Tracer
//	      deps: *example.com/servoorders/internal/observability.Config
//	      capabilities: Finalizer | binding: sole candidate | internal/observability/tracing.go:29:6
//	[L1] *github.com/okian/servo/v3/middleware.AccessLog
//	      deps: none
//	      capabilities: none | binding: sole candidate | /Users/kian/servo/middleware/accesslog.go:14:6
//	[L2] *example.com/servoorders/internal/auth.Config
//	      deps: *example.com/servoorders/internal/config.Env
//	      capabilities: none | binding: sole candidate | internal/auth/auth.go:35:6
//	[L3] *example.com/servoorders/internal/auth.Issuer
//	      deps: *example.com/servoorders/internal/auth.Config
//	      capabilities: none | binding: sole candidate | internal/auth/auth.go:39:6
//	[L4] *example.com/servoorders/internal/transport/servoapi.Auth
//	      deps: *example.com/servoorders/internal/auth.Issuer
//	      capabilities: none | binding: sole candidate | internal/transport/servoapi/middleware.go:32:6
//	[L2] *example.com/servoorders/internal/repository/postgres.Config
//	      deps: *example.com/servoorders/internal/config.Env
//	      capabilities: none | binding: sole candidate | internal/repository/postgres/postgres.go:37:6
//	[L3] *example.com/servoorders/internal/repository/postgres.Store
//	      deps: *example.com/servoorders/internal/repository/postgres.Config
//	      capabilities: Initializer, Finalizer, Healther | binding: explicit bind | internal/repository/postgres/postgres.go:41:6
//	[L4] *example.com/servoorders/internal/service.AuthService
//	      deps: *example.com/servoorders/internal/repository/postgres.Store, *example.com/servoorders/internal/auth.Issuer
//	      capabilities: none | binding: sole candidate | internal/service/auth_service.go:18:6
//	[L2] *example.com/servoorders/internal/cache/redis.Config
//	      deps: *example.com/servoorders/internal/config.Env
//	      capabilities: none | binding: sole candidate | internal/cache/redis/redis.go:36:6
//	[L3] *example.com/servoorders/internal/cache/redis.Cache
//	      deps: *example.com/servoorders/internal/cache/redis.Config
//	      capabilities: Initializer, Finalizer, Healther | binding: sole candidate | internal/cache/redis/redis.go:40:6
//	[L4] *example.com/servoorders/internal/resilience.CircuitBreakerCache
//	      deps: *example.com/servoorders/internal/cache/redis.Cache
//	      capabilities: none | binding: explicit bind | internal/resilience/breaker.go:38:6
//	[L2] *example.com/servoorders/internal/broker/natsbroker.Config
//	      deps: *example.com/servoorders/internal/config.Env
//	      capabilities: none | binding: sole candidate | internal/broker/natsbroker/natsbroker.go:35:6
//	[L3] *example.com/servoorders/internal/broker/natsbroker.Publisher
//	      deps: *example.com/servoorders/internal/broker/natsbroker.Config
//	      capabilities: Initializer, Finalizer, Healther | binding: explicit bind | internal/broker/natsbroker/natsbroker.go:46:6
//	[L5] *example.com/servoorders/internal/service.OrderService
//	      deps: *example.com/servoorders/internal/repository/postgres.Store, *example.com/servoorders/internal/resilience.CircuitBreakerCache, *example.com/servoorders/internal/broker/natsbroker.Publisher, *example.com/servoorders/internal/observability.Logger
//	      capabilities: none | binding: sole candidate | internal/service/service.go:28:6
//
// scope example.com/servoorders/internal/session.UserID
//
//	linger: 5m0s | max: 50000
//	accessor: example.com/servoorders/internal/session.Sessions -> *example.com/servoorders/internal/session.Session
//	[S1] *example.com/servoorders/internal/session.Session
//	      capabilities: Initializer, Flusher, Finalizer
//	borrows: *example.com/servoorders/internal/session.Config, *example.com/servoorders/internal/observability.Logger
//
// http (servo.HTTP() at cmd/ordersservo/spec.go:31:3):
//
//	config: *github.com/okian/servo/v3/servo.HTTPConfig
//	use: *github.com/okian/servo/v3/middleware.Recover -> every group
//	use: *example.com/servoorders/internal/resilience.RateLimiter -> every group
//	use: *example.com/servoorders/internal/observability.Tracer -> every group
//	use: *example.com/servoorders/internal/observability.Metrics -> every group
//	use: *github.com/okian/servo/v3/middleware.AccessLog -> every group
//	use: *example.com/servoorders/internal/transport/servoapi.Auth -> POST /orders, GET /orders/{id}, GET /orders, GET /me/recent
//	extract: *example.com/servoorders/internal/transport/servoapi.ClaimsExtractor -> example.com/servoorders/internal/auth.Claims
//	POST /auth/login -> servoapi.Login (internal/transport/servoapi/handlers.go:18:1)
//	      args: *example.com/servoorders/internal/service.AuthService
//	GET /me/recent -> servoapi.Recent (internal/transport/servoapi/handlers.go:88:1)
//	      args: example.com/servoorders/internal/auth.Claims (extracted), example.com/servoorders/internal/session.Sessions
//	GET /orders -> servoapi.ListOrders (internal/transport/servoapi/handlers.go:62:1)
//	      args: example.com/servoorders/internal/auth.Claims (extracted), *example.com/servoorders/internal/service.OrderService
//	POST /orders -> servoapi.CreateOrder (internal/transport/servoapi/handlers.go:31:1)
//	      args: example.com/servoorders/internal/auth.Claims (extracted), *example.com/servoorders/internal/service.OrderService
//	GET /orders/{id} -> servoapi.GetOrder (internal/transport/servoapi/handlers.go:45:1)
//	      args: example.com/servoorders/internal/auth.Claims (extracted), *example.com/servoorders/internal/service.OrderService, example.com/servoorders/internal/session.Sessions
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"sync"
	"sync/atomic"
	"syscall"
	"time"

	"example.com/servoorders/internal/auth"
	"example.com/servoorders/internal/broker/natsbroker"
	"example.com/servoorders/internal/cache/redis"
	"example.com/servoorders/internal/config"
	"example.com/servoorders/internal/observability"
	"example.com/servoorders/internal/repository/postgres"
	"example.com/servoorders/internal/resilience"
	"example.com/servoorders/internal/service"
	"example.com/servoorders/internal/session"
	"example.com/servoorders/internal/transport/servoapi"
	"github.com/okian/servo/v3/middleware"
	"github.com/okian/servo/v3/servo"
	"golang.org/x/sync/errgroup"
)

type App struct {
	env                   *config.Env
	sessionConfig         *session.Config
	observabilityConfig   *observability.Config
	logger                *observability.Logger
	hTTPConfig            *servo.HTTPConfig
	claimsExtractor       *servoapi.ClaimsExtractor
	recover2              *middleware.Recover
	resilienceConfig      *resilience.Config
	metrics               *observability.Metrics
	rateLimiter           *resilience.RateLimiter
	tracer                *observability.Tracer
	tracerStopOnce        sync.Once
	tracerStopResult      servo.NodeResult
	accessLog             *middleware.AccessLog
	authConfig            *auth.Config
	issuer                *auth.Issuer
	auth                  *servoapi.Auth
	postgresConfig        *postgres.Config
	store                 *postgres.Store
	storeStopOnce         sync.Once
	storeStopResult       servo.NodeResult
	authService           *service.AuthService
	redisConfig           *redis.Config
	cache                 *redis.Cache
	cacheStopOnce         sync.Once
	cacheStopResult       servo.NodeResult
	circuitBreakerCache   *resilience.CircuitBreakerCache
	natsbrokerConfig      *natsbroker.Config
	publisher             *natsbroker.Publisher
	publisherStopOnce     sync.Once
	publisherStopResult   servo.NodeResult
	orderService          *service.OrderService
	userIDScope           *userIDScope
	sessions              sessionsAccessor
	userIDScopeStopOnce   sync.Once
	userIDScopeStopResult servo.NodeResult
	httpServer            *httpServer
	httpServerStopOnce    sync.Once
	httpServerStopResult  servo.NodeResult
	startupReport         servo.StartupReport
}

// userIDScope is the registry for scope example.com/servoorders/internal/session.UserID. One entry per live key, each
// owning its own reference count and linger timer in its own goroutine.
type userIDScope struct {
	app    *App
	mu     sync.RWMutex
	items  map[session.UserID]*userIDEntry
	closed bool
	// quit is closed once, by Shutdown, and read by every entry loop.
	quit chan struct{}

	// base is New's context with cancellation stripped. An instance
	// outlives the request that created it, so hanging its Run loop off
	// an acquirer's context would kill it the moment that one caller
	// disconnects, while the instance is still live and referenced.
	// Values propagate; cancellation does not.
	base   context.Context
	linger time.Duration
	max    int

	refs      atomic.Int64
	acquires  atomic.Uint64
	evictions atomic.Uint64
	// failures counts evictions whose teardown did not come out clean.
	// An instance evicted mid-life has no Report to appear in — Shutdown
	// is not running — so without this a Drain that failed or a Stop that
	// overran its budget would leave no trace anywhere.
	failures atomic.Uint64
	// tearing holds entries that have left items but are still draining
	// and stopping. Removal has to happen first, so a racing acquirer's
	// retry misses — but an entry in this window is still very much an
	// instance: Shutdown has to wait for it, Max has to count it, and
	// Stats must not report the scope quiet while it is running.
	tearing map[*userIDEntry]struct{}
}

func newUserIDScope(ctx context.Context, app *App) *userIDScope {
	return &userIDScope{
		app:     app,
		items:   map[session.UserID]*userIDEntry{},
		tearing: map[*userIDEntry]struct{}{},
		quit:    make(chan struct{}),
		base:    context.WithoutCancel(ctx),
		linger:  servo.LingerWindow(5 * time.Minute),
		max:     50000,
	}
}

func (s *userIDScope) Stats() servo.ScopeStats {
	s.mu.RLock()
	live := s.liveLocked()
	s.mu.RUnlock()
	return servo.ScopeStats{Live: live, Refs: int(s.refs.Load()), Acquires: s.acquires.Load(), Evictions: s.evictions.Load(), Failures: s.failures.Load()}
}

// liveLocked is how many instances exist: mapped, plus those that have
// left the map but are still tearing down. Callers hold s.mu.
func (s *userIDScope) liveLocked() int { return len(s.items) + len(s.tearing) }

// lookupOrCreate takes the read lock on the hit path and the write lock,
// with a second look, on the miss path: sync.RWMutex has no atomic
// upgrade, so two cold acquires of the same key would otherwise both
// create, orphaning one entry and the goroutine it was about to start.
func (s *userIDScope) lookupOrCreate(key session.UserID) (*userIDEntry, bool, error) {
	s.mu.RLock()
	e, ok := s.items[key]
	closed := s.closed
	s.mu.RUnlock()
	if closed {
		return nil, false, servo.ErrScopeClosed
	}
	if ok {
		return e, false, nil
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	if e, ok := s.items[key]; ok {
		return e, false, nil
	}
	if s.closed {
		return nil, false, servo.ErrScopeClosed
	}
	// Counts tearing entries too: they still hold their instance and its
	// memory, so admitting past them would make Max a bound on map size
	// rather than on live instances.
	if s.liveLocked() >= s.max {
		return nil, false, servo.ErrScopeFull
	}
	ctx, cancel := context.WithCancel(s.base)
	e = &userIDEntry{
		scope: s, key: key, ctx: ctx, cancel: cancel,
		joins: make(chan struct{}), leaves: make(chan struct{}),
		ready: make(chan struct{}), dead: make(chan struct{}), torn: make(chan struct{}),
	}
	s.items[key] = e
	return e, true, nil
}

// remove deletes key only while it still maps to this exact entry. A
// dying entry is never revived — a new incarnation is a new entry with a
// new goroutine — and that replacement may already have claimed the key.
func (s *userIDScope) remove(key session.UserID, e *userIDEntry) {
	s.mu.Lock()
	if s.items[key] == e {
		delete(s.items, key)
	}
	s.mu.Unlock()
}

// beginTeardown moves an entry out of the map and into tearing in one
// step. Both have to happen under the same lock: an entry visible in
// neither set is one Shutdown would not wait for and Max would not count.
func (s *userIDScope) beginTeardown(e *userIDEntry) {
	s.mu.Lock()
	s.tearing[e] = struct{}{}
	if s.items[e.key] == e {
		delete(s.items, e.key)
	}
	s.mu.Unlock()
}

// endTeardown drops the entry and counts the eviction in one critical
// section. Counting after the unlock would let Live reach zero before
// Evictions was bumped — and since Live reaching zero is the
// documented way to wait for a scope to go quiet, a test that waited
// that way and then read Evictions could observe the instance gone
// and its eviction uncounted.
func (s *userIDScope) endTeardown(e *userIDEntry, result servo.NodeResult) {
	s.mu.Lock()
	delete(s.tearing, e)
	s.evictions.Add(1)
	if result.Status != servo.StatusOK {
		s.failures.Add(1)
	}
	s.mu.Unlock()
}

// abandon unwinds an entry whose construction failed, so it leaves
// nothing behind in the map and any waiter gets the error rather than
// blocking on an instance that will never exist.
func (s *userIDScope) abandon(e *userIDEntry, err error) error {
	s.remove(e.key, e)
	e.cancel()
	e.buildErr = err
	// stopResult stays OK: nothing was constructed, so nothing was torn
	// down. The error goes to the acquirer that caused it — folding it
	// into Shutdown's report as well would make one bad key at the wrong
	// instant render the whole shutdown dirty.
	e.stopResult = servo.NodeResult{Name: e.name(), Status: servo.StatusOK}
	close(e.dead)
	close(e.torn)
	return err
}

// userIDEntry is one live key's instances plus the channels its loop
// selects on. Everything mutable about the reference count lives inside
// that loop as a local variable, so there is nothing here to lock.
type userIDEntry struct {
	scope  *userIDScope
	key    session.UserID
	ctx    context.Context
	cancel context.CancelFunc

	joins  chan struct{}
	leaves chan struct{}
	// ready closes when construction succeeded; dead closes when the key
	// has been removed from the map, which happens strictly first so a
	// racing acquirer's retry misses and creates fresh instead of finding
	// the same corpse forever. torn closes when teardown has finished.
	ready chan struct{}
	dead  chan struct{}
	torn  chan struct{}

	// built is how many members build() has finished assigning. The
	// error path unrolls a known prefix; the panic path cannot know
	// how far it got, so it reads this.
	built      int
	buildErr   error
	stopResult servo.NodeResult
	// drainResult is set only when the reference drain overran its
	// budget, so this instance was stopped while a caller still held
	// it. Written by the entry's own loop and read by teardown on the
	// same goroutine, so it needs no lock.
	drainResult servo.NodeResult
	runWG       sync.WaitGroup
	runMu       sync.Mutex
	runErrs     []error
	session     *session.Session
}

func (e *userIDEntry) name() string {
	return fmt.Sprintf("%s[%v]", "scope example.com/servoorders/internal/session.UserID", e.key)
}

// loop owns this entry's reference count. A join is acknowledged by the
// receive itself, so an acquirer knows its reference is counted before it
// returns, and the loop never blocks on a caller that has walked away.
//
// It starts at one, not zero: whoever built this entry holds the first
// reference by construction and never sends a join for it. Starting at
// zero would leave an entry whose creator gave up before joining alive
// with no reference and no timer armed — live forever, held by nobody.
func (e *userIDEntry) loop() {
	refs := 1
	var timer *time.Timer
	var linger <-chan time.Time
	stopTimer := func() {
		if timer != nil {
			timer.Stop()
			timer = nil
		}
		linger = nil
	}
	for {
		// Checked before the blocking select, so that once Shutdown has
		// closed quit this loop stops accepting joins instead of racing
		// them. A join and a quit both ready in one select is a coin
		// flip, and losing it hands an acquirer an instance this
		// iteration is about to tear down.
		select {
		case <-e.scope.quit:
			stopTimer()
			e.drainRefs(refs)
			e.evict()
			return
		default:
		}

		select {
		case <-e.joins:
			refs++
			stopTimer()
		case <-e.leaves:
			refs--
			if refs == 0 {
				// The window before eviction. Without it a short handler
				// takes the count 0->1->0 per request and the instance is
				// rebuilt every time, losing whatever in-memory state made
				// it worth sharing.
				stopTimer()
				timer = time.NewTimer(e.scope.linger)
				linger = timer.C
			}
		case <-linger:
			timer, linger = nil, nil
			e.evict()
			return
		case <-e.scope.quit:
			stopTimer()
			e.drainRefs(refs)
			e.evict()
			return
		}
	}
}

// drainRefs waits for the holders outstanding when Shutdown arrived to
// give their references back before teardown starts. A counted
// reference is a promise that the instance stays usable until it is
// released, and evicting under a live holder would break that promise
// for the one caller who did everything right: acquired successfully,
// a moment before someone else called Shutdown.
//
// In the ordinary case there is nothing to wait for. Shutdown stops
// nodes in reverse level order, so whatever depends on this scope has
// already been drained and stopped, its handlers have returned and
// their releases have already landed.
//
// Bounded by one stop budget, because a caller who never releases must
// not hold shutdown open. Overrunning that bound is recorded in
// drainResult, which teardown merges, so the entry comes back
// abandoned: the report is the only place a promise broken this way
// could show, and a clean one would hide it entirely.
func (e *userIDEntry) drainRefs(refs int) {
	if refs <= 0 {
		return
	}
	budget := time.NewTimer(servo.DefaultStopBudget)
	defer budget.Stop()
	for refs > 0 {
		select {
		case <-e.leaves:
			refs--
		case <-budget.C:
			err := fmt.Errorf("servo: torn down with %d reference(s) still held after %s", refs, servo.DefaultStopBudget)
			e.drainResult = servo.NodeResult{Name: e.name(), Status: servo.StatusAbandoned, Err: err}
			return
		}
	}
}

// evict removes the key from the map BEFORE announcing the entry's death.
// Reversed, an acquirer that lost the join race would retry, look the key
// up, find this same dying entry, and never terminate.
func (e *userIDEntry) evict() {
	e.scope.beginTeardown(e)
	close(e.dead)
	e.stopResult = e.teardown()
	e.scope.endTeardown(e, e.stopResult)
	close(e.torn)
}

// build constructs this entry's instances and runs their Init phase, in
// the same level order and with the same rollback shape as the App's own
// constructor. It runs in the acquiring goroutine, not under the scope's
// lock, so one slow constructor cannot freeze every other key.
func (e *userIDEntry) build() error {
	a := e.scope.app

	session := session.New(e.key, a.sessionConfig, a.logger)
	e.session = session
	e.built = 1

	if err := e.session.Init(e.ctx); err != nil {
		e.stopSession(context.Background())
		return err
	}
	return nil
}

func (e *userIDEntry) stopSession(ctx context.Context) []servo.NodeResult {
	var results []servo.NodeResult
	results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoorders/internal/session.Session", e.session.Flush))
	results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoorders/internal/session.Session", e.session.Stop))
	return results
}

// rollback stops whatever build() managed to construct, newest first.
// The error paths inside build() unroll a known prefix inline; this is
// for the panic path, which cannot know how far it got.
func (e *userIDEntry) rollback() {
	ctx := context.Background()
	if e.built > 0 {
		e.stopSession(ctx)
	}
}

// teardown runs on a fresh context, for the same reason main hands
// Shutdown one: the drain has to survive the cancellation that triggered
// it. No deadline is set here because there is no caller to take one
// from — a linger timer can fire this — and servo.RunStop bounds every
// call below at servo.DefaultStopBudget either way. Drain comes first so
// a streaming consumer unblocks before its context is pulled out from
// under it; Flush comes after the Run goroutines have returned, so
// anything Run buffered is flushed rather than discarded.
func (e *userIDEntry) teardown() servo.NodeResult {
	ctx := context.Background()
	var results []servo.NodeResult
	// Set only when the reference drain overran its budget, so this
	// instance is being stopped while someone still holds it.
	if e.drainResult.Status != servo.StatusOK {
		results = append(results, e.drainResult)
	}
	e.cancel()
	results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, e.name(), e.waitRun))
	results = append(results, e.stopSession(ctx)...)
	return servo.MergeNodeResults(e.name(), results...)
}

func (e *userIDEntry) waitRun(context.Context) error {
	e.runWG.Wait()
	e.runMu.Lock()
	defer e.runMu.Unlock()
	return errors.Join(e.runErrs...)
}

// waitTorn blocks until this entry has finished tearing down. Shutdown
// calls it through servo.RunStop so the wait is bounded.
func (e *userIDEntry) waitTorn(ctx context.Context) error {
	select {
	case <-e.torn:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}

// acquireSession resolves ctx to a key, then hands back the instance for that
// key and a closure that releases it. The reference unit is the caller's
// use of the instance, not the lifetime of ctx: cancellation is not
// completion, and a client disconnecting mid-handler must not free an
// instance whose deferred cleanups are still running.
func (s *userIDScope) acquireSession(ctx context.Context) (*session.Session, func(), error) {
	// A context that can never be done disables the release backstop
	// below, so a caller who forgets the closure would pin this instance
	// for the life of the process. Refusing is the only way to say so.
	if ctx.Done() == nil {
		return nil, nil, servo.ErrNoLifetime
	}
	// Called on a typed nil: the key has to be known before an instance
	// can be chosen, so there is no instance to call it on. Safe because
	// servo rejects a ScopeKey method whose receiver its body could reach.
	var zero *session.Session
	key, err := zero.ScopeKey(ctx)
	if err != nil {
		return nil, nil, err
	}

	for {
		e, created, err := s.lookupOrCreate(key)
		if err != nil {
			return nil, nil, err
		}
		if created {
			if err := s.start(e); err != nil {
				return nil, nil, err
			}
			// The loop is running now, and its very first select may have
			// taken quit. Handing back an instance that is already torn
			// down would be worse than refusing: the retry sees the scope
			// closed and says so.
			select {
			case <-e.dead:
				continue
			default:
			}
			s.refs.Add(1)
			s.acquires.Add(1)
			return e.session, e.releaser(ctx), nil
		}

		select {
		case <-e.ready:
		case <-e.dead:
			if e.buildErr != nil {
				return nil, nil, e.buildErr
			}
			continue
		case <-ctx.Done():
			return nil, nil, ctx.Err()
		}

		select {
		case e.joins <- struct{}{}:
			s.refs.Add(1)
			s.acquires.Add(1)
			return e.session, e.releaser(ctx), nil
		case <-e.dead:
			// Lost the race with eviction. The retry misses the map — the
			// key was removed before dead closed — and creates fresh.
			continue
		case <-s.quit:
			// Shutdown began while this acquirer was waiting to join. The
			// loop has stopped reading joins and is draining the holders it
			// already has, so waiting here would block for that drain only
			// to be told the scope is closed. Say so now. If the join and
			// this case are ready together the choice is arbitrary and
			// either answer is correct: a join that lands is a counted
			// reference the drain will wait for.
			return nil, nil, servo.ErrScopeClosed
		case <-ctx.Done():
			return nil, nil, ctx.Err()
		}
	}
}

func (s *userIDScope) start(entry *userIDEntry) (err error) {
	started := false
	defer func() {
		if started {
			return
		}
		if r := recover(); r != nil {
			entry.rollback()
			err = s.abandon(entry, fmt.Errorf("servo: panic constructing %s: %v", entry.name(), r))
		}
	}()

	if err := entry.build(); err != nil {
		started = true // the unwind below is not ours; build already rolled back
		return s.abandon(entry, err)
	}
	go entry.loop()
	close(entry.ready)
	started = true
	return nil
}

// releaser returns the closure the caller defers, with ctx ending as a
// backstop behind it. Both paths run the same sync.Once, so a caller who
// forgets the closure still releases when their request ends — later
// than ideal, but not never.
func (e *userIDEntry) releaser(ctx context.Context) func() {
	var once sync.Once
	release := func() {
		once.Do(func() {
			e.scope.refs.Add(-1)
			select {
			case e.leaves <- struct{}{}:
			case <-e.dead:
			}
		})
	}
	stop := context.AfterFunc(ctx, release)
	return func() {
		stop()
		release()
	}
}

// sessionsAccessor is what satisfies example.com/servoorders/internal/session.Sessions. It is a distinct type per
// exposed root so that two roots sharing one scope can each have a method
// literally named Acquire.
type sessionsAccessor struct{ s *userIDScope }

func (x sessionsAccessor) Acquire(ctx context.Context) (*session.Session, func(), error) {
	return x.s.acquireSession(ctx)
}

func (x sessionsAccessor) Stats() servo.ScopeStats { return x.s.Stats() }

const defaultMaxBodyBytes = 1 << 20

// httpServer serves the default group's //servo: routes. It is generated
// machinery, not a graph node: its dependencies are ordinary singletons
// on the App, resolved once at construction.
type httpServer struct {
	app     *App
	lc      servo.HTTPListener
	srv     *http.Server
	maxBody int64
	// ready flips once the listener is bound, which is the precise moment
	// Ready starts reporting ok for the "http" node.
	ready atomic.Bool
}

func newHttpServer(a *App) (*httpServer, error) {
	cfg := a.hTTPConfig
	lc := servo.HTTPListener{
		IP:           cfg.IP,
		Port:         cfg.Port,
		CertFile:     cfg.CertFile,
		KeyFile:      cfg.KeyFile,
		MaxBodyBytes: cfg.MaxBodyBytes,
		ReadTimeout:  cfg.ReadTimeout,
		WriteTimeout: cfg.WriteTimeout,
		IdleTimeout:  cfg.IdleTimeout,
	}
	s := &httpServer{app: a, lc: lc}
	s.maxBody = lc.MaxBodyBytes
	if s.maxBody <= 0 {
		s.maxBody = defaultMaxBodyBytes
	}
	mux := http.NewServeMux()
	mux.HandleFunc("POST /auth/login", s.handleLogin)
	{
		var h http.Handler = http.HandlerFunc(s.handleRecent)
		h = a.auth.Middleware(h)
		mux.Handle("GET /me/recent", h)
	}
	{
		var h http.Handler = http.HandlerFunc(s.handleListOrders)
		h = a.auth.Middleware(h)
		mux.Handle("GET /orders", h)
	}
	{
		var h http.Handler = http.HandlerFunc(s.handleCreateOrder)
		h = a.auth.Middleware(h)
		mux.Handle("POST /orders", h)
	}
	{
		var h http.Handler = http.HandlerFunc(s.handleGetOrder)
		h = a.auth.Middleware(h)
		mux.Handle("GET /orders/{id}", h)
	}
	var handler http.Handler = mux
	handler = a.accessLog.Middleware(handler)
	handler = a.metrics.Middleware(handler)
	handler = a.tracer.Middleware(handler)
	handler = a.rateLimiter.Middleware(handler)
	handler = a.recover2.Middleware(handler)
	s.srv = &http.Server{
		Addr:         net.JoinHostPort(lc.IP, strconv.FormatUint(uint64(lc.Port), 10)),
		Handler:      handler,
		ReadTimeout:  lc.ReadTimeout,
		WriteTimeout: lc.WriteTimeout,
		IdleTimeout:  lc.IdleTimeout,
	}
	return s, nil
}

func (s *httpServer) handleLogin(w http.ResponseWriter, r *http.Request) {
	req := &servoapi.LoginReq{}
	// The body decodes first, so the explicitly bound sources below
	// overwrite anything it could smuggle into a same-named field.
	r.Body = http.MaxBytesReader(w, r.Body, s.maxBody)
	if err := json.NewDecoder(r.Body).Decode(req); err != nil {
		httpWriteError(w, http.StatusBadRequest, "malformed request body")
		return
	}
	res, err := servoapi.Login(r.Context(), req, s.app.authService)
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "servoapi.Login", "POST /auth/login", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpServer) handleRecent(w http.ResponseWriter, r *http.Request) {
	claims, err := s.app.claimsExtractor.Extract(r)
	if err != nil {
		httpWriteFailure(w, "servoapi.Recent", "GET /me/recent", err)
		return
	}
	res, err := servoapi.Recent(r.Context(), claims, s.app.sessions)
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "servoapi.Recent", "GET /me/recent", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpServer) handleListOrders(w http.ResponseWriter, r *http.Request) {
	req := &servoapi.ListOrdersReq{}
	q := r.URL.Query()
	if raw := q.Get("limit"); raw != "" {
		v, err := strconv.ParseInt(raw, 10, 0)
		if err != nil {
			httpWriteError(w, http.StatusBadRequest, "query parameter \"limit\" is not a valid int")
			return
		}
		req.Limit = int(v)
	}
	if raw := q.Get("offset"); raw != "" {
		v, err := strconv.ParseInt(raw, 10, 0)
		if err != nil {
			httpWriteError(w, http.StatusBadRequest, "query parameter \"offset\" is not a valid int")
			return
		}
		req.Offset = int(v)
	}
	claims, err := s.app.claimsExtractor.Extract(r)
	if err != nil {
		httpWriteFailure(w, "servoapi.ListOrders", "GET /orders", err)
		return
	}
	res, err := servoapi.ListOrders(r.Context(), req, claims, s.app.orderService)
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "servoapi.ListOrders", "GET /orders", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpServer) handleCreateOrder(w http.ResponseWriter, r *http.Request) {
	req := &servoapi.CreateOrderReq{}
	// The body decodes first, so the explicitly bound sources below
	// overwrite anything it could smuggle into a same-named field.
	r.Body = http.MaxBytesReader(w, r.Body, s.maxBody)
	if err := json.NewDecoder(r.Body).Decode(req); err != nil {
		httpWriteError(w, http.StatusBadRequest, "malformed request body")
		return
	}
	claims, err := s.app.claimsExtractor.Extract(r)
	if err != nil {
		httpWriteFailure(w, "servoapi.CreateOrder", "POST /orders", err)
		return
	}
	res, err := servoapi.CreateOrder(r.Context(), req, claims, s.app.orderService)
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "servoapi.CreateOrder", "POST /orders", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpServer) handleGetOrder(w http.ResponseWriter, r *http.Request) {
	req := &servoapi.GetOrderReq{}
	req.ID = r.PathValue("id")
	claims, err := s.app.claimsExtractor.Extract(r)
	if err != nil {
		httpWriteFailure(w, "servoapi.GetOrder", "GET /orders/{id}", err)
		return
	}
	res, err := servoapi.GetOrder(r.Context(), req, claims, s.app.orderService, s.app.sessions)
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "servoapi.GetOrder", "GET /orders/{id}", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpServer) run(ctx context.Context) error {
	ln, err := net.Listen("tcp", s.srv.Addr)
	if err != nil {
		return fmt.Errorf("http: listen %s: %w", s.srv.Addr, err)
	}
	s.ready.Store(true)
	serveErr := make(chan error, 1)
	go func() {
		var err error
		if s.lc.CertFile != "" && s.lc.KeyFile != "" {
			err = s.srv.ServeTLS(ln, s.lc.CertFile, s.lc.KeyFile)
		} else {
			err = s.srv.Serve(ln)
		}
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			serveErr <- err
			return
		}
		serveErr <- nil
	}()
	select {
	case <-ctx.Done():
		return nil
	case err := <-serveErr:
		return err
	}
}

// httpRespond writes one success response; a nil response means status only,
// no body. Encoding lives in the runtime's sealed Response family, so a
// handler may return any of its kinds through this one helper.
func httpRespond(w http.ResponseWriter, code int, res servo.Response) {
	if res == nil {
		w.WriteHeader(code)
		return
	}
	if err := servo.WriteResponse(w, code, res); err != nil {
		slog.Error("servo: writing response failed", "error", err)
	}
}

// httpWriteFailure maps a handler or extractor error onto the response: a status in
// the chain picks the code, 4xx bodies carry the message, 5xx bodies only
// the canonical text — the wrapped detail is for the log, not the client.
func httpWriteFailure(w http.ResponseWriter, handler, route string, err error) {
	var hs servo.HTTPStatus
	if !errors.As(err, &hs) {
		slog.Error("servo: handler "+handler+" failed", "route", route, "error", err)
		httpWriteError(w, http.StatusInternalServerError, "Internal Server Error")
		return
	}
	code := hs.Code()
	if code >= 500 {
		slog.Error("servo: handler "+handler+" failed", "route", route, "status", code, "error", err)
		httpWriteError(w, code, hs.Error())
		return
	}
	httpWriteError(w, code, err.Error())
}

func httpWriteError(w http.ResponseWriter, code int, msg string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(struct {
		Error string `json:"error"`
	}{Error: msg})
}

func New(ctx context.Context) (*App, error) {
	a := &App{}

	a.userIDScope = newUserIDScope(ctx, a)
	a.sessions = sessionsAccessor{s: a.userIDScope}

	env := config.NewEnv()
	a.env = env

	sessionConfig, err := session.NewConfig(env)
	if err != nil {
		return nil, err
	}
	a.sessionConfig = sessionConfig

	observabilityConfig, err := observability.NewConfig(env)
	if err != nil {
		return nil, err
	}
	a.observabilityConfig = observabilityConfig

	logger := observability.NewLogger(observabilityConfig)
	a.logger = logger

	hTTPConfig, err := servoapi.NewHTTPConfig(env)
	if err != nil {
		return nil, err
	}
	a.hTTPConfig = hTTPConfig

	claimsExtractor := servoapi.NewClaimsExtractor()
	a.claimsExtractor = claimsExtractor

	recover2 := middleware.NewRecover()
	a.recover2 = recover2

	resilienceConfig, err := resilience.NewConfig(env)
	if err != nil {
		return nil, err
	}
	a.resilienceConfig = resilienceConfig

	metrics := observability.NewMetrics()
	a.metrics = metrics

	rateLimiter := resilience.NewRateLimiter(resilienceConfig, metrics)
	a.rateLimiter = rateLimiter

	tracer, err := observability.NewTracer(observabilityConfig)
	if err != nil {
		return nil, err
	}
	a.tracer = tracer

	accessLog := middleware.NewAccessLog()
	a.accessLog = accessLog

	authConfig, err := auth.NewConfig(env)
	if err != nil {
		_ = a.stopTracer(ctx)
		return nil, err
	}
	a.authConfig = authConfig

	issuer := auth.New(authConfig)
	a.issuer = issuer

	auth := servoapi.NewAuth(issuer)
	a.auth = auth

	postgresConfig, err := postgres.NewConfig(env)
	if err != nil {
		_ = a.stopTracer(ctx)
		return nil, err
	}
	a.postgresConfig = postgresConfig

	store, err := postgres.New(postgresConfig)
	if err != nil {
		_ = a.stopTracer(ctx)
		return nil, err
	}
	a.store = store

	authService := service.NewAuthService(store, issuer)
	a.authService = authService

	redisConfig, err := redis.NewConfig(env)
	if err != nil {
		_ = a.stopStore(ctx)
		_ = a.stopTracer(ctx)
		return nil, err
	}
	a.redisConfig = redisConfig

	cache := redis.New(redisConfig)
	a.cache = cache

	circuitBreakerCache := resilience.NewCircuitBreakerCache(cache)
	a.circuitBreakerCache = circuitBreakerCache

	natsbrokerConfig, err := natsbroker.NewConfig(env)
	if err != nil {
		_ = a.stopCache(ctx)
		_ = a.stopStore(ctx)
		_ = a.stopTracer(ctx)
		return nil, err
	}
	a.natsbrokerConfig = natsbrokerConfig

	publisher := natsbroker.New(natsbrokerConfig)
	a.publisher = publisher

	orderService := service.New(store, circuitBreakerCache, publisher, logger)
	a.orderService = orderService

	{
		var timingMu sync.Mutex
		g, gctx := errgroup.WithContext(ctx)
		g.Go(func() error {
			start := time.Now()
			err := a.store.Init(gctx)
			timingMu.Lock()
			a.startupReport.Nodes = append(a.startupReport.Nodes, servo.StartupNode{Type: "*example.com/servoorders/internal/repository/postgres.Store", Duration: time.Since(start)})
			timingMu.Unlock()
			return err
		})
		g.Go(func() error {
			start := time.Now()
			err := a.cache.Init(gctx)
			timingMu.Lock()
			a.startupReport.Nodes = append(a.startupReport.Nodes, servo.StartupNode{Type: "*example.com/servoorders/internal/cache/redis.Cache", Duration: time.Since(start)})
			timingMu.Unlock()
			return err
		})
		g.Go(func() error {
			start := time.Now()
			err := a.publisher.Init(gctx)
			timingMu.Lock()
			a.startupReport.Nodes = append(a.startupReport.Nodes, servo.StartupNode{Type: "*example.com/servoorders/internal/broker/natsbroker.Publisher", Duration: time.Since(start)})
			timingMu.Unlock()
			return err
		})
		if err := g.Wait(); err != nil {
			report := a.Shutdown(ctx)
			return nil, errors.Join(err, report)
		}
	}
	httpServer, err := newHttpServer(a)
	if err != nil {
		report := a.Shutdown(ctx)
		return nil, errors.Join(err, report)
	}
	a.httpServer = httpServer

	return a, nil
}

func (a *App) stopTracer(ctx context.Context) servo.NodeResult {
	a.tracerStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoorders/internal/observability.Tracer", a.tracer.Stop))
		a.tracerStopResult = servo.MergeNodeResults("*example.com/servoorders/internal/observability.Tracer", results...)
	})
	return a.tracerStopResult
}

func (a *App) stopStore(ctx context.Context) servo.NodeResult {
	a.storeStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoorders/internal/repository/postgres.Store", a.store.Stop))
		a.storeStopResult = servo.MergeNodeResults("*example.com/servoorders/internal/repository/postgres.Store", results...)
	})
	return a.storeStopResult
}

func (a *App) stopCache(ctx context.Context) servo.NodeResult {
	a.cacheStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoorders/internal/cache/redis.Cache", a.cache.Stop))
		a.cacheStopResult = servo.MergeNodeResults("*example.com/servoorders/internal/cache/redis.Cache", results...)
	})
	return a.cacheStopResult
}

func (a *App) stopPublisher(ctx context.Context) servo.NodeResult {
	a.publisherStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoorders/internal/broker/natsbroker.Publisher", a.publisher.Stop))
		a.publisherStopResult = servo.MergeNodeResults("*example.com/servoorders/internal/broker/natsbroker.Publisher", results...)
	})
	return a.publisherStopResult
}

func (a *App) stopUserIDScope(ctx context.Context) servo.NodeResult {
	a.userIDScopeStopOnce.Do(func() {
		s := a.userIDScope
		s.mu.Lock()
		if !s.closed {
			s.closed = true
			close(s.quit)
		}
		// Both sets, not just items: an entry that began evicting a moment
		// ago has already left the map, and waiting only on what is mapped
		// would let Shutdown return while its Drain and Flush were still
		// running — against singletons this very function is about to stop.
		entries := make([]*userIDEntry, 0, s.liveLocked())
		for _, e := range s.items {
			entries = append(entries, e)
		}
		for e := range s.tearing {
			entries = append(entries, e)
		}
		s.mu.Unlock()

		results := make([]servo.NodeResult, 0, len(entries))
		// Budgeted like every other stop call, so an instance wedged in a
		// constructor or a Drain is reported abandoned rather than holding
		// the whole shutdown open past the deadline its caller passed. The
		// multiplier is the number of budgeted calls one teardown makes
		// (4 here): a single budget would time out on an entry that was
		// tearing down perfectly correctly, and report it abandoned.
		for _, e := range entries {
			if res := servo.RunStop(ctx, 4*servo.DefaultStopBudget, e.name(), e.waitTorn); res.Status != servo.StatusOK {
				results = append(results, res)
				continue
			}
			results = append(results, e.stopResult)
		}
		a.userIDScopeStopResult = servo.MergeNodeResults("scope example.com/servoorders/internal/session.UserID", results...)
	})
	return a.userIDScopeStopResult
}

func (a *App) stopHttpServer(ctx context.Context) servo.NodeResult {
	a.httpServerStopOnce.Do(func() {
		if a.httpServer == nil {
			a.httpServerStopResult = servo.NodeResult{Name: "http", Status: servo.StatusOK}
			return
		}
		a.httpServerStopResult = servo.RunStop(ctx, servo.DefaultStopBudget, "http", a.httpServer.srv.Shutdown)
	})
	return a.httpServerStopResult
}

func (a *App) Run(ctx context.Context) error {
	return a.httpServer.run(ctx)
}

func (a *App) Shutdown(ctx context.Context) servo.Report {
	forceExit := make(chan os.Signal, 1)
	signal.Notify(forceExit, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(forceExit)
	watcherDone := make(chan struct{})
	defer close(watcherDone)
	go func() {
		select {
		case <-forceExit:
			os.Exit(1)
		case <-watcherDone:
		}
	}()

	var nodes []servo.NodeResult
	nodes = append(nodes, a.stopHttpServer(ctx))
	nodes = append(nodes, a.stopUserIDScope(ctx))
	nodes = append(nodes, a.stopPublisher(ctx))
	nodes = append(nodes, a.stopCache(ctx))
	nodes = append(nodes, a.stopStore(ctx))
	nodes = append(nodes, a.stopTracer(ctx))
	return servo.Report{Nodes: nodes}
}

// HTTPHandler returns the named group's routed, middleware-wrapped handler
// — for httptest, which needs no bound listener. "" and "default" name the
// default group; unknown names return nil.
func (a *App) HTTPHandler(group string) http.Handler {
	switch group {
	case "", "default":
		return a.httpServer.srv.Handler
	}
	return nil
}

func (a *App) Health(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	if err := a.store.Health(ctx); err != nil {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servoorders/internal/repository/postgres.Store", Status: servo.StatusFailed, Err: err})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servoorders/internal/repository/postgres.Store", Status: servo.StatusOK})
	}
	if err := a.cache.Health(ctx); err != nil {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servoorders/internal/cache/redis.Cache", Status: servo.StatusFailed, Err: err})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servoorders/internal/cache/redis.Cache", Status: servo.StatusOK})
	}
	if err := a.publisher.Health(ctx); err != nil {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servoorders/internal/broker/natsbroker.Publisher", Status: servo.StatusFailed, Err: err})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servoorders/internal/broker/natsbroker.Publisher", Status: servo.StatusOK})
	}
	return servo.Report{Nodes: nodes}
}

func (a *App) Ready(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	if a.httpServer != nil && a.httpServer.ready.Load() {
		nodes = append(nodes, servo.NodeResult{Name: "http", Status: servo.StatusOK})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "http", Status: servo.StatusFailed, Err: errors.New("http: not accepting connections yet")})
	}
	return servo.Report{Nodes: nodes}
}

func (a *App) Graph() servo.Graph {
	return servo.Graph{Nodes: []servo.GraphNode{
		{Type: "*example.com/servoorders/internal/config.Env", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole implementation", Pos: "internal/config/config.go:42:6"},
		{Type: "*example.com/servoorders/internal/session.Config", Level: 2, Deps: []string{"*example.com/servoorders/internal/config.Env"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/session/session.go:66:6"},
		{Type: "*example.com/servoorders/internal/observability.Config", Level: 2, Deps: []string{"*example.com/servoorders/internal/config.Env"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/observability/logging.go:21:6"},
		{Type: "*example.com/servoorders/internal/observability.Logger", Level: 3, Deps: []string{"*example.com/servoorders/internal/observability.Config"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/observability/logging.go:35:6"},
		{Type: "*github.com/okian/servo/v3/servo.HTTPConfig", Level: 2, Deps: []string{"*example.com/servoorders/internal/config.Env"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/transport/servoapi/middleware.go:88:6"},
		{Type: "*example.com/servoorders/internal/transport/servoapi.ClaimsExtractor", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "internal/transport/servoapi/middleware.go:69:6"},
		{Type: "*github.com/okian/servo/v3/middleware.Recover", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "/Users/kian/servo/middleware/recover.go:17:6"},
		{Type: "*example.com/servoorders/internal/resilience.Config", Level: 2, Deps: []string{"*example.com/servoorders/internal/config.Env"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/resilience/ratelimit.go:29:6"},
		{Type: "*example.com/servoorders/internal/observability.Metrics", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "internal/observability/metrics.go:18:6"},
		{Type: "*example.com/servoorders/internal/resilience.RateLimiter", Level: 3, Deps: []string{"*example.com/servoorders/internal/resilience.Config", "*example.com/servoorders/internal/observability.Metrics"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/resilience/ratelimit.go:33:6"},
		{Type: "*example.com/servoorders/internal/observability.Tracer", Level: 3, Deps: []string{"*example.com/servoorders/internal/observability.Config"}, Capabilities: []string{"Finalizer"}, Binding: "sole candidate", Pos: "internal/observability/tracing.go:29:6"},
		{Type: "*github.com/okian/servo/v3/middleware.AccessLog", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "/Users/kian/servo/middleware/accesslog.go:14:6"},
		{Type: "*example.com/servoorders/internal/auth.Config", Level: 2, Deps: []string{"*example.com/servoorders/internal/config.Env"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/auth/auth.go:35:6"},
		{Type: "*example.com/servoorders/internal/auth.Issuer", Level: 3, Deps: []string{"*example.com/servoorders/internal/auth.Config"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/auth/auth.go:39:6"},
		{Type: "*example.com/servoorders/internal/transport/servoapi.Auth", Level: 4, Deps: []string{"*example.com/servoorders/internal/auth.Issuer"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/transport/servoapi/middleware.go:32:6"},
		{Type: "*example.com/servoorders/internal/repository/postgres.Config", Level: 2, Deps: []string{"*example.com/servoorders/internal/config.Env"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/repository/postgres/postgres.go:37:6"},
		{Type: "*example.com/servoorders/internal/repository/postgres.Store", Level: 3, Deps: []string{"*example.com/servoorders/internal/repository/postgres.Config"}, Capabilities: []string{"Initializer", "Finalizer", "Healther"}, Binding: "explicit bind", Pos: "internal/repository/postgres/postgres.go:41:6"},
		{Type: "*example.com/servoorders/internal/service.AuthService", Level: 4, Deps: []string{"*example.com/servoorders/internal/repository/postgres.Store", "*example.com/servoorders/internal/auth.Issuer"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/service/auth_service.go:18:6"},
		{Type: "*example.com/servoorders/internal/cache/redis.Config", Level: 2, Deps: []string{"*example.com/servoorders/internal/config.Env"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/cache/redis/redis.go:36:6"},
		{Type: "*example.com/servoorders/internal/cache/redis.Cache", Level: 3, Deps: []string{"*example.com/servoorders/internal/cache/redis.Config"}, Capabilities: []string{"Initializer", "Finalizer", "Healther"}, Binding: "sole candidate", Pos: "internal/cache/redis/redis.go:40:6"},
		{Type: "*example.com/servoorders/internal/resilience.CircuitBreakerCache", Level: 4, Deps: []string{"*example.com/servoorders/internal/cache/redis.Cache"}, Capabilities: nil, Binding: "explicit bind", Pos: "internal/resilience/breaker.go:38:6"},
		{Type: "*example.com/servoorders/internal/broker/natsbroker.Config", Level: 2, Deps: []string{"*example.com/servoorders/internal/config.Env"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/broker/natsbroker/natsbroker.go:35:6"},
		{Type: "*example.com/servoorders/internal/broker/natsbroker.Publisher", Level: 3, Deps: []string{"*example.com/servoorders/internal/broker/natsbroker.Config"}, Capabilities: []string{"Initializer", "Finalizer", "Healther"}, Binding: "explicit bind", Pos: "internal/broker/natsbroker/natsbroker.go:46:6"},
		{Type: "*example.com/servoorders/internal/service.OrderService", Level: 5, Deps: []string{"*example.com/servoorders/internal/repository/postgres.Store", "*example.com/servoorders/internal/resilience.CircuitBreakerCache", "*example.com/servoorders/internal/broker/natsbroker.Publisher", "*example.com/servoorders/internal/observability.Logger"}, Capabilities: nil, Binding: "sole candidate", Pos: "internal/service/service.go:28:6"},
		{Type: "*example.com/servoorders/internal/session.Session", Level: 1, Deps: []string{"example.com/servoorders/internal/session.UserID", "*example.com/servoorders/internal/session.Config", "*example.com/servoorders/internal/observability.Logger"}, Capabilities: []string{"Initializer", "Flusher", "Finalizer"}, Binding: "sole candidate", Pos: "internal/session/session.go:70:6", Scope: "example.com/servoorders/internal/session.UserID"},
	}, Scopes: []servo.GraphScope{
		{Key: "example.com/servoorders/internal/session.UserID", Linger: "5m0s", Max: 50000, Accessors: []string{"example.com/servoorders/internal/session.Sessions"}, Members: []string{"*example.com/servoorders/internal/session.Session"}, Borrows: []string{"*example.com/servoorders/internal/session.Config", "*example.com/servoorders/internal/observability.Logger"}},
	}, HTTP: &servo.GraphHTTP{
		Routes: []servo.GraphRoute{
			{Method: "POST", Pattern: "/auth/login", Handler: "servoapi.Login", Args: []string{"*example.com/servoorders/internal/service.AuthService"}, Pos: "internal/transport/servoapi/handlers.go:18:1"},
			{Method: "GET", Pattern: "/me/recent", Handler: "servoapi.Recent", Args: []string{"example.com/servoorders/internal/auth.Claims (extracted)", "example.com/servoorders/internal/session.Sessions"}, Pos: "internal/transport/servoapi/handlers.go:88:1"},
			{Method: "GET", Pattern: "/orders", Handler: "servoapi.ListOrders", Args: []string{"example.com/servoorders/internal/auth.Claims (extracted)", "*example.com/servoorders/internal/service.OrderService"}, Pos: "internal/transport/servoapi/handlers.go:62:1"},
			{Method: "POST", Pattern: "/orders", Handler: "servoapi.CreateOrder", Args: []string{"example.com/servoorders/internal/auth.Claims (extracted)", "*example.com/servoorders/internal/service.OrderService"}, Pos: "internal/transport/servoapi/handlers.go:31:1"},
			{Method: "GET", Pattern: "/orders/{id}", Handler: "servoapi.GetOrder", Args: []string{"example.com/servoorders/internal/auth.Claims (extracted)", "*example.com/servoorders/internal/service.OrderService", "example.com/servoorders/internal/session.Sessions"}, Pos: "internal/transport/servoapi/handlers.go:45:1"},
		},
		Uses: []servo.GraphUse{
			{Type: "*github.com/okian/servo/v3/middleware.Recover", Scope: "server"},
			{Type: "*example.com/servoorders/internal/resilience.RateLimiter", Scope: "server"},
			{Type: "*example.com/servoorders/internal/observability.Tracer", Scope: "server"},
			{Type: "*example.com/servoorders/internal/observability.Metrics", Scope: "server"},
			{Type: "*github.com/okian/servo/v3/middleware.AccessLog", Scope: "server"},
			{Type: "*example.com/servoorders/internal/transport/servoapi.Auth", Scope: "route POST /orders, GET /orders/{id}, GET /orders, GET /me/recent"},
		},
		Extractors: []servo.GraphExtractor{
			{Type: "*example.com/servoorders/internal/transport/servoapi.ClaimsExtractor", Produces: "example.com/servoorders/internal/auth.Claims"},
		},
	}}
}

func (a *App) Report() servo.StartupReport {
	return a.startupReport
}
