//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// Resolved graph:
//
//	[L1] *example.com/servoscoped/logger.Logger
//	      deps: none
//	      capabilities: Finalizer | binding: sole candidate | logger/logger.go:16:6
//	[L2] *example.com/servoscoped/api.Server
//	      deps: example.com/servoscoped/chat.Rooms, *example.com/servoscoped/logger.Logger
//	      capabilities: Runner, Drainer, Finalizer | binding: sole candidate | api/api.go:19:6
//
// scope example.com/servoscoped/chat.RoomKey
//
//	linger: 30s | max: 10000
//	accessor: example.com/servoscoped/chat.Rooms -> *example.com/servoscoped/chat.Room
//	[S1] *example.com/servoscoped/chat.RoomLog
//	      capabilities: Initializer, Flusher
//	[S2] *example.com/servoscoped/chat.Room
//	      capabilities: Initializer, Runner, Drainer, Finalizer
//	borrows: *example.com/servoscoped/logger.Logger
package main

import (
	"context"
	"errors"
	"example.com/servoscoped/api"
	"example.com/servoscoped/chat"
	"example.com/servoscoped/logger"
	"fmt"
	"github.com/okian/servo/v3/servo"
	"os"
	"os/signal"
	"sync"
	"sync/atomic"
	"syscall"
	"time"
)

type App struct {
	logger                 *logger.Logger
	loggerStopOnce         sync.Once
	loggerStopResult       servo.NodeResult
	server                 *api.Server
	serverStopOnce         sync.Once
	serverStopResult       servo.NodeResult
	roomKeyScope           *roomKeyScope
	rooms                  roomsAccessor
	roomKeyScopeStopOnce   sync.Once
	roomKeyScopeStopResult servo.NodeResult
	startupReport          servo.StartupReport
}

// roomKeyScope is the registry for scope example.com/servoscoped/chat.RoomKey. One entry per live key, each
// owning its own reference count and linger timer in its own goroutine.
type roomKeyScope struct {
	app    *App
	mu     sync.RWMutex
	items  map[chat.RoomKey]*roomKeyEntry
	closed bool
	// quit is closed once, by Shutdown, and read by every entry loop.
	quit chan struct{}

	// base is New's context with cancellation stripped. An instance
	// outlives the request that created it, so hanging its Run loop off
	// an acquirer's context would kill it the moment that one caller
	// disconnects, while the instance is still live and referenced.
	// Values propagate; cancellation does not.
	base   context.Context
	linger time.Duration
	max    int

	refs      atomic.Int64
	acquires  atomic.Uint64
	evictions atomic.Uint64
	// failures counts evictions whose teardown did not come out clean.
	// An instance evicted mid-life has no Report to appear in — Shutdown
	// is not running — so without this a Drain that failed or a Stop that
	// overran its budget would leave no trace anywhere.
	failures atomic.Uint64
	// tearing holds entries that have left items but are still draining
	// and stopping. Removal has to happen first, so a racing acquirer's
	// retry misses — but an entry in this window is still very much an
	// instance: Shutdown has to wait for it, Max has to count it, and
	// Stats must not report the scope quiet while it is running.
	tearing map[*roomKeyEntry]struct{}
}

func newRoomKeyScope(ctx context.Context, app *App) *roomKeyScope {
	return &roomKeyScope{
		app:     app,
		items:   map[chat.RoomKey]*roomKeyEntry{},
		tearing: map[*roomKeyEntry]struct{}{},
		quit:    make(chan struct{}),
		base:    context.WithoutCancel(ctx),
		linger:  servo.LingerWindow(30 * time.Second),
		max:     10000,
	}
}

func (s *roomKeyScope) Stats() servo.ScopeStats {
	s.mu.RLock()
	live := s.liveLocked()
	s.mu.RUnlock()
	return servo.ScopeStats{Live: live, Refs: int(s.refs.Load()), Acquires: s.acquires.Load(), Evictions: s.evictions.Load(), Failures: s.failures.Load()}
}

// liveLocked is how many instances exist: mapped, plus those that have
// left the map but are still tearing down. Callers hold s.mu.
func (s *roomKeyScope) liveLocked() int { return len(s.items) + len(s.tearing) }

// lookupOrCreate takes the read lock on the hit path and the write lock,
// with a second look, on the miss path: sync.RWMutex has no atomic
// upgrade, so two cold acquires of the same key would otherwise both
// create, orphaning one entry and the goroutine it was about to start.
func (s *roomKeyScope) lookupOrCreate(key chat.RoomKey) (*roomKeyEntry, bool, error) {
	s.mu.RLock()
	e, ok := s.items[key]
	closed := s.closed
	s.mu.RUnlock()
	if closed {
		return nil, false, servo.ErrScopeClosed
	}
	if ok {
		return e, false, nil
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	if e, ok := s.items[key]; ok {
		return e, false, nil
	}
	if s.closed {
		return nil, false, servo.ErrScopeClosed
	}
	// Counts tearing entries too: they still hold their instance and its
	// memory, so admitting past them would make Max a bound on map size
	// rather than on live instances.
	if s.liveLocked() >= s.max {
		return nil, false, servo.ErrScopeFull
	}
	ctx, cancel := context.WithCancel(s.base)
	e = &roomKeyEntry{
		scope: s, key: key, ctx: ctx, cancel: cancel,
		joins: make(chan struct{}), leaves: make(chan struct{}),
		ready: make(chan struct{}), dead: make(chan struct{}), torn: make(chan struct{}),
	}
	s.items[key] = e
	return e, true, nil
}

// remove deletes key only while it still maps to this exact entry. A
// dying entry is never revived — a new incarnation is a new entry with a
// new goroutine — and that replacement may already have claimed the key.
func (s *roomKeyScope) remove(key chat.RoomKey, e *roomKeyEntry) {
	s.mu.Lock()
	if s.items[key] == e {
		delete(s.items, key)
	}
	s.mu.Unlock()
}

// beginTeardown moves an entry out of the map and into tearing in one
// step. Both have to happen under the same lock: an entry visible in
// neither set is one Shutdown would not wait for and Max would not count.
func (s *roomKeyScope) beginTeardown(e *roomKeyEntry) {
	s.mu.Lock()
	s.tearing[e] = struct{}{}
	if s.items[e.key] == e {
		delete(s.items, e.key)
	}
	s.mu.Unlock()
}

// endTeardown drops the entry and counts the eviction in one critical
// section. Counting after the unlock would let Live reach zero before
// Evictions was bumped — and since Live reaching zero is the
// documented way to wait for a scope to go quiet, a test that waited
// that way and then read Evictions could observe the instance gone
// and its eviction uncounted.
func (s *roomKeyScope) endTeardown(e *roomKeyEntry, result servo.NodeResult) {
	s.mu.Lock()
	delete(s.tearing, e)
	s.evictions.Add(1)
	if result.Status != servo.StatusOK {
		s.failures.Add(1)
	}
	s.mu.Unlock()
}

// abandon unwinds an entry whose construction failed, so it leaves
// nothing behind in the map and any waiter gets the error rather than
// blocking on an instance that will never exist.
func (s *roomKeyScope) abandon(e *roomKeyEntry, err error) error {
	s.remove(e.key, e)
	e.cancel()
	e.buildErr = err
	// stopResult stays OK: nothing was constructed, so nothing was torn
	// down. The error goes to the acquirer that caused it — folding it
	// into Shutdown's report as well would make one bad key at the wrong
	// instant render the whole shutdown dirty.
	e.stopResult = servo.NodeResult{Name: e.name(), Status: servo.StatusOK}
	close(e.dead)
	close(e.torn)
	return err
}

// roomKeyEntry is one live key's instances plus the channels its loop
// selects on. Everything mutable about the reference count lives inside
// that loop as a local variable, so there is nothing here to lock.
type roomKeyEntry struct {
	scope  *roomKeyScope
	key    chat.RoomKey
	ctx    context.Context
	cancel context.CancelFunc

	joins  chan struct{}
	leaves chan struct{}
	// ready closes when construction succeeded; dead closes when the key
	// has been removed from the map, which happens strictly first so a
	// racing acquirer's retry misses and creates fresh instead of finding
	// the same corpse forever. torn closes when teardown has finished.
	ready chan struct{}
	dead  chan struct{}
	torn  chan struct{}

	// built is how many members build() has finished assigning. The
	// error path unrolls a known prefix; the panic path cannot know
	// how far it got, so it reads this.
	built      int
	buildErr   error
	stopResult servo.NodeResult
	// drainResult is set only when the reference drain overran its
	// budget, so this instance was stopped while a caller still held
	// it. Written by the entry's own loop and read by teardown on the
	// same goroutine, so it needs no lock.
	drainResult servo.NodeResult
	runWG       sync.WaitGroup
	runMu       sync.Mutex
	runErrs     []error
	roomLog     *chat.RoomLog
	room        *chat.Room
}

func (e *roomKeyEntry) name() string {
	return fmt.Sprintf("%s[%v]", "scope example.com/servoscoped/chat.RoomKey", e.key)
}

// loop owns this entry's reference count. A join is acknowledged by the
// receive itself, so an acquirer knows its reference is counted before it
// returns, and the loop never blocks on a caller that has walked away.
//
// It starts at one, not zero: whoever built this entry holds the first
// reference by construction and never sends a join for it. Starting at
// zero would leave an entry whose creator gave up before joining alive
// with no reference and no timer armed — live forever, held by nobody.
func (e *roomKeyEntry) loop() {
	refs := 1
	var timer *time.Timer
	var linger <-chan time.Time
	stopTimer := func() {
		if timer != nil {
			timer.Stop()
			timer = nil
		}
		linger = nil
	}
	for {
		// Checked before the blocking select, so that once Shutdown has
		// closed quit this loop stops accepting joins instead of racing
		// them. A join and a quit both ready in one select is a coin
		// flip, and losing it hands an acquirer an instance this
		// iteration is about to tear down.
		select {
		case <-e.scope.quit:
			stopTimer()
			e.drainRefs(refs)
			e.evict()
			return
		default:
		}

		select {
		case <-e.joins:
			refs++
			stopTimer()
		case <-e.leaves:
			refs--
			if refs == 0 {
				// The window before eviction. Without it a short handler
				// takes the count 0->1->0 per request and the instance is
				// rebuilt every time, losing whatever in-memory state made
				// it worth sharing.
				stopTimer()
				timer = time.NewTimer(e.scope.linger)
				linger = timer.C
			}
		case <-linger:
			timer, linger = nil, nil
			e.evict()
			return
		case <-e.scope.quit:
			stopTimer()
			e.drainRefs(refs)
			e.evict()
			return
		}
	}
}

// drainRefs waits for the holders outstanding when Shutdown arrived to
// give their references back before teardown starts. A counted
// reference is a promise that the instance stays usable until it is
// released, and evicting under a live holder would break that promise
// for the one caller who did everything right: acquired successfully,
// a moment before someone else called Shutdown.
//
// In the ordinary case there is nothing to wait for. Shutdown stops
// nodes in reverse level order, so whatever depends on this scope has
// already been drained and stopped, its handlers have returned and
// their releases have already landed.
//
// Bounded by one stop budget, because a caller who never releases must
// not hold shutdown open. Overrunning that bound is recorded in
// drainResult, which teardown merges, so the entry comes back
// abandoned: the report is the only place a promise broken this way
// could show, and a clean one would hide it entirely.
func (e *roomKeyEntry) drainRefs(refs int) {
	if refs <= 0 {
		return
	}
	budget := time.NewTimer(servo.DefaultStopBudget)
	defer budget.Stop()
	for refs > 0 {
		select {
		case <-e.leaves:
			refs--
		case <-budget.C:
			err := fmt.Errorf("servo: torn down with %d reference(s) still held after %s", refs, servo.DefaultStopBudget)
			e.drainResult = servo.NodeResult{Name: e.name(), Status: servo.StatusAbandoned, Err: err}
			return
		}
	}
}

// evict removes the key from the map BEFORE announcing the entry's death.
// Reversed, an acquirer that lost the join race would retry, look the key
// up, find this same dying entry, and never terminate.
func (e *roomKeyEntry) evict() {
	e.scope.beginTeardown(e)
	close(e.dead)
	e.stopResult = e.teardown()
	e.scope.endTeardown(e, e.stopResult)
	close(e.torn)
}

// build constructs this entry's instances and runs their Init phase, in
// the same level order and with the same rollback shape as the App's own
// constructor. It runs in the acquiring goroutine, not under the scope's
// lock, so one slow constructor cannot freeze every other key.
func (e *roomKeyEntry) build() error {
	a := e.scope.app

	roomLog := chat.NewRoomLog(e.key, a.logger)
	e.roomLog = roomLog
	e.built = 1

	room, err := chat.NewRoom(e.key, e.roomLog)
	if err != nil {
		e.stopRoomLog(context.Background())
		return err
	}
	e.room = room
	e.built = 2

	if err := e.roomLog.Init(e.ctx); err != nil {
		e.drainRoom(context.Background())
		e.stopRoom(context.Background())
		e.stopRoomLog(context.Background())
		return err
	}
	if err := e.room.Init(e.ctx); err != nil {
		e.drainRoom(context.Background())
		e.stopRoom(context.Background())
		e.stopRoomLog(context.Background())
		return err
	}

	// One goroutine per running instance, on the entry's own context. A
	// Run that returns because that context was cancelled is a normal
	// teardown, not a failure, and is not reported as one.
	e.runWG.Add(1)
	go func() {
		defer e.runWG.Done()
		if err := e.room.Run(e.ctx); err != nil && !errors.Is(err, context.Canceled) {
			e.runMu.Lock()
			e.runErrs = append(e.runErrs, err)
			e.runMu.Unlock()
		}
	}()

	return nil
}

func (e *roomKeyEntry) stopRoomLog(ctx context.Context) []servo.NodeResult {
	var results []servo.NodeResult
	results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoscoped/chat.RoomLog", e.roomLog.Flush))
	return results
}

func (e *roomKeyEntry) drainRoom(ctx context.Context) []servo.NodeResult {
	return []servo.NodeResult{servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoscoped/chat.Room", e.room.Drain)}
}

func (e *roomKeyEntry) stopRoom(ctx context.Context) []servo.NodeResult {
	var results []servo.NodeResult
	results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoscoped/chat.Room", e.room.Stop))
	return results
}

// rollback stops whatever build() managed to construct, newest first.
// The error paths inside build() unroll a known prefix inline; this is
// for the panic path, which cannot know how far it got.
func (e *roomKeyEntry) rollback() {
	ctx := context.Background()
	if e.built > 1 {
		e.drainRoom(ctx)
		e.stopRoom(ctx)
	}
	if e.built > 0 {
		e.stopRoomLog(ctx)
	}
}

// teardown runs on a fresh context.Background(), for the same reason the
// generated main calls Shutdown(context.Background()): the drain has to
// survive the cancellation that triggered it. Drain comes first so a
// streaming consumer unblocks before its context is pulled out from
// under it; Flush comes after the Run goroutines have returned, so
// anything Run buffered is flushed rather than discarded.
func (e *roomKeyEntry) teardown() servo.NodeResult {
	ctx := context.Background()
	var results []servo.NodeResult
	// Set only when the reference drain overran its budget, so this
	// instance is being stopped while someone still holds it.
	if e.drainResult.Status != servo.StatusOK {
		results = append(results, e.drainResult)
	}
	results = append(results, e.drainRoom(ctx)...)
	e.cancel()
	results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, e.name(), e.waitRun))
	results = append(results, e.stopRoom(ctx)...)
	results = append(results, e.stopRoomLog(ctx)...)
	return servo.MergeNodeResults(e.name(), results...)
}

func (e *roomKeyEntry) waitRun(context.Context) error {
	e.runWG.Wait()
	e.runMu.Lock()
	defer e.runMu.Unlock()
	return errors.Join(e.runErrs...)
}

// waitTorn blocks until this entry has finished tearing down. Shutdown
// calls it through servo.RunStop so the wait is bounded.
func (e *roomKeyEntry) waitTorn(ctx context.Context) error {
	select {
	case <-e.torn:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}

// acquireRoom resolves ctx to a key, then hands back the instance for that
// key and a closure that releases it. The reference unit is the caller's
// use of the instance, not the lifetime of ctx: cancellation is not
// completion, and a client disconnecting mid-handler must not free an
// instance whose deferred cleanups are still running.
func (s *roomKeyScope) acquireRoom(ctx context.Context) (*chat.Room, func(), error) {
	// A context that can never be done disables the release backstop
	// below, so a caller who forgets the closure would pin this instance
	// for the life of the process. Refusing is the only way to say so.
	if ctx.Done() == nil {
		return nil, nil, servo.ErrNoLifetime
	}
	// Called on a typed nil: the key has to be known before an instance
	// can be chosen, so there is no instance to call it on. Safe because
	// servo rejects a ScopeKey method whose receiver its body could reach.
	var zero *chat.Room
	key, err := zero.ScopeKey(ctx)
	if err != nil {
		return nil, nil, err
	}

	for {
		e, created, err := s.lookupOrCreate(key)
		if err != nil {
			return nil, nil, err
		}
		if created {
			if err := s.start(e); err != nil {
				return nil, nil, err
			}
			// The loop is running now, and its very first select may have
			// taken quit. Handing back an instance that is already torn
			// down would be worse than refusing: the retry sees the scope
			// closed and says so.
			select {
			case <-e.dead:
				continue
			default:
			}
			s.refs.Add(1)
			s.acquires.Add(1)
			return e.room, e.releaser(ctx), nil
		}

		select {
		case <-e.ready:
		case <-e.dead:
			if e.buildErr != nil {
				return nil, nil, e.buildErr
			}
			continue
		case <-ctx.Done():
			return nil, nil, ctx.Err()
		}

		select {
		case e.joins <- struct{}{}:
			s.refs.Add(1)
			s.acquires.Add(1)
			return e.room, e.releaser(ctx), nil
		case <-e.dead:
			// Lost the race with eviction. The retry misses the map — the
			// key was removed before dead closed — and creates fresh.
			continue
		case <-s.quit:
			// Shutdown began while this acquirer was waiting to join. The
			// loop has stopped reading joins and is draining the holders it
			// already has, so waiting here would block for that drain only
			// to be told the scope is closed. Say so now. If the join and
			// this case are ready together the choice is arbitrary and
			// either answer is correct: a join that lands is a counted
			// reference the drain will wait for.
			return nil, nil, servo.ErrScopeClosed
		case <-ctx.Done():
			return nil, nil, ctx.Err()
		}
	}
}

func (s *roomKeyScope) start(entry *roomKeyEntry) (err error) {
	started := false
	defer func() {
		if started {
			return
		}
		if r := recover(); r != nil {
			entry.rollback()
			err = s.abandon(entry, fmt.Errorf("servo: panic constructing %s: %v", entry.name(), r))
		}
	}()

	if err := entry.build(); err != nil {
		started = true // the unwind below is not ours; build already rolled back
		return s.abandon(entry, err)
	}
	go entry.loop()
	close(entry.ready)
	started = true
	return nil
}

// releaser returns the closure the caller defers, with ctx ending as a
// backstop behind it. Both paths run the same sync.Once, so a caller who
// forgets the closure still releases when their request ends — later
// than ideal, but not never.
func (e *roomKeyEntry) releaser(ctx context.Context) func() {
	var once sync.Once
	release := func() {
		once.Do(func() {
			e.scope.refs.Add(-1)
			select {
			case e.leaves <- struct{}{}:
			case <-e.dead:
			}
		})
	}
	stop := context.AfterFunc(ctx, release)
	return func() {
		stop()
		release()
	}
}

// roomsAccessor is what satisfies example.com/servoscoped/chat.Rooms. It is a distinct type per
// exposed root so that two roots sharing one scope can each have a method
// literally named Acquire.
type roomsAccessor struct{ s *roomKeyScope }

func (x roomsAccessor) Acquire(ctx context.Context) (*chat.Room, func(), error) {
	return x.s.acquireRoom(ctx)
}

func (x roomsAccessor) Stats() servo.ScopeStats { return x.s.Stats() }

func New(ctx context.Context) (*App, error) {
	a := &App{}

	a.roomKeyScope = newRoomKeyScope(ctx, a)
	a.rooms = roomsAccessor{s: a.roomKeyScope}

	logger := logger.New()
	a.logger = logger

	server := api.New(a.rooms, logger)
	a.server = server

	return a, nil
}

func (a *App) stopLogger(ctx context.Context) servo.NodeResult {
	a.loggerStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoscoped/logger.Logger", a.logger.Stop))
		a.loggerStopResult = servo.MergeNodeResults("*example.com/servoscoped/logger.Logger", results...)
	})
	return a.loggerStopResult
}

func (a *App) stopServer(ctx context.Context) servo.NodeResult {
	a.serverStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoscoped/api.Server", a.server.Drain))
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoscoped/api.Server", a.server.Stop))
		a.serverStopResult = servo.MergeNodeResults("*example.com/servoscoped/api.Server", results...)
	})
	return a.serverStopResult
}

func (a *App) stopRoomKeyScope(ctx context.Context) servo.NodeResult {
	a.roomKeyScopeStopOnce.Do(func() {
		s := a.roomKeyScope
		s.mu.Lock()
		if !s.closed {
			s.closed = true
			close(s.quit)
		}
		// Both sets, not just items: an entry that began evicting a moment
		// ago has already left the map, and waiting only on what is mapped
		// would let Shutdown return while its Drain and Flush were still
		// running — against singletons this very function is about to stop.
		entries := make([]*roomKeyEntry, 0, s.liveLocked())
		for _, e := range s.items {
			entries = append(entries, e)
		}
		for e := range s.tearing {
			entries = append(entries, e)
		}
		s.mu.Unlock()

		results := make([]servo.NodeResult, 0, len(entries))
		// Budgeted like every other stop call, so an instance wedged in a
		// constructor or a Drain is reported abandoned rather than holding
		// the whole shutdown open past the deadline its caller passed. The
		// multiplier is the number of budgeted calls one teardown makes
		// (5 here): a single budget would time out on an entry that was
		// tearing down perfectly correctly, and report it abandoned.
		for _, e := range entries {
			if res := servo.RunStop(ctx, 5*servo.DefaultStopBudget, e.name(), e.waitTorn); res.Status != servo.StatusOK {
				results = append(results, res)
				continue
			}
			results = append(results, e.stopResult)
		}
		a.roomKeyScopeStopResult = servo.MergeNodeResults("scope example.com/servoscoped/chat.RoomKey", results...)
	})
	return a.roomKeyScopeStopResult
}

func (a *App) Run(ctx context.Context) error {
	return a.server.Run(ctx)
}

func (a *App) Shutdown(ctx context.Context) servo.Report {
	forceExit := make(chan os.Signal, 1)
	signal.Notify(forceExit, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(forceExit)
	watcherDone := make(chan struct{})
	defer close(watcherDone)
	go func() {
		select {
		case <-forceExit:
			os.Exit(1)
		case <-watcherDone:
		}
	}()

	var nodes []servo.NodeResult
	nodes = append(nodes, a.stopServer(ctx))
	nodes = append(nodes, a.stopRoomKeyScope(ctx))
	nodes = append(nodes, a.stopLogger(ctx))
	return servo.Report{Nodes: nodes}
}

func (a *App) Health(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Ready(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Graph() servo.Graph {
	return servo.Graph{Nodes: []servo.GraphNode{
		{Type: "*example.com/servoscoped/logger.Logger", Level: 1, Deps: nil, Capabilities: []string{"Finalizer"}, Binding: "sole candidate", Pos: "logger/logger.go:16:6"},
		{Type: "*example.com/servoscoped/api.Server", Level: 2, Deps: []string{"example.com/servoscoped/chat.Rooms", "*example.com/servoscoped/logger.Logger"}, Capabilities: []string{"Runner", "Drainer", "Finalizer"}, Binding: "sole candidate", Pos: "api/api.go:19:6"},
		{Type: "*example.com/servoscoped/chat.RoomLog", Level: 1, Deps: []string{"example.com/servoscoped/chat.RoomKey", "*example.com/servoscoped/logger.Logger"}, Capabilities: []string{"Initializer", "Flusher"}, Binding: "sole candidate", Pos: "chat/chat.go:174:6", Scope: "example.com/servoscoped/chat.RoomKey"},
		{Type: "*example.com/servoscoped/chat.Room", Level: 2, Deps: []string{"example.com/servoscoped/chat.RoomKey", "*example.com/servoscoped/chat.RoomLog"}, Capabilities: []string{"Initializer", "Runner", "Drainer", "Finalizer"}, Binding: "sole candidate", Pos: "chat/chat.go:74:6", Scope: "example.com/servoscoped/chat.RoomKey"},
	}, Scopes: []servo.GraphScope{
		{Key: "example.com/servoscoped/chat.RoomKey", Linger: "30s", Max: 10000, Accessors: []string{"example.com/servoscoped/chat.Rooms"}, Members: []string{"*example.com/servoscoped/chat.RoomLog", "*example.com/servoscoped/chat.Room"}, Borrows: []string{"*example.com/servoscoped/logger.Logger"}},
	}}
}

func (a *App) Report() servo.StartupReport {
	return a.startupReport
}
