//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// ServoConfig fills config from the process environment.
// Settings:
//
//	POSTGRES_DSN string, required
package postgres

import (
	"fmt"
	"os"
	"strings"
)

// ServoConfig builds config. Precedence per setting: default, then the POSTGRES_* environment
// variable — the environment always wins.
func ServoConfig() (config, error) {
	var cfg config
	var missing []string

	// dsn — POSTGRES_DSN (required)
	if v, ok := os.LookupEnv("POSTGRES_DSN"); ok {
		cfg.dsn = v
	} else {
		missing = append(missing, "POSTGRES_DSN")
	}

	if len(missing) > 0 {
		return config{}, fmt.Errorf("postgres: missing required configuration: %s", strings.Join(missing, ", "))
	}
	return cfg, nil
}
