//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// ServoConfig fills Config from the process environment.
// Settings:
//
//	POSTGRES_DSN string, required
package postgres

import (
	"fmt"
	"os"
	"strings"
)

// ServoConfig builds Config. Precedence per setting: default, then the POSTGRES_* environment
// variable — the environment always wins.
func ServoConfig() (Config, error) {
	var cfg Config
	var missing []string

	// dsn — POSTGRES_DSN (required)
	if v, ok := os.LookupEnv("POSTGRES_DSN"); ok {
		cfg.DSN = v
	} else {
		missing = append(missing, "POSTGRES_DSN")
	}

	if len(missing) > 0 {
		return Config{}, fmt.Errorf("postgres: missing required configuration: %s", strings.Join(missing, ", "))
	}
	return cfg, nil
}
