//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// Resolved graph:
//
//	[L1] *example.com/servobasic/logger.Logger
//	      deps: none
//	      capabilities: Finalizer | binding: sole candidate | logger/logger.go:10:6
//	[L2] *example.com/servobasic/postgres.DB
//	      deps: *example.com/servobasic/logger.Logger
//	      capabilities: Initializer, Finalizer, Healther | binding: sole candidate | postgres/postgres.go:13:6
//	[L3] *example.com/servobasic/migrator.Migrator
//	      deps: *example.com/servobasic/postgres.DB, *example.com/servobasic/logger.Logger
//	      capabilities: Initializer | binding: sole candidate | migrator/migrator.go:15:6
package main

import (
	"context"
	"errors"
	"example.com/servobasic/logger"
	"example.com/servobasic/migrator"
	"example.com/servobasic/postgres"
	"github.com/okian/servo/v3/servo"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"
)

type App struct {
	logger           *logger.Logger
	loggerStopOnce   sync.Once
	loggerStopResult servo.NodeResult
	db               *postgres.DB
	dbStopOnce       sync.Once
	dbStopResult     servo.NodeResult
	migrator         *migrator.Migrator
	startupReport    servo.StartupReport
}

func New(ctx context.Context) (*App, error) {
	a := &App{}

	logger := logger.New()
	a.logger = logger

	db, err := postgres.New(logger)
	if err != nil {
		_ = a.stopLogger(ctx)
		return nil, err
	}
	a.db = db

	migrator := migrator.New(db, logger)
	a.migrator = migrator

	{
		start := time.Now()
		err := a.db.Init(ctx)
		a.startupReport.Nodes = append(a.startupReport.Nodes, servo.StartupNode{Type: "*example.com/servobasic/postgres.DB", Duration: time.Since(start)})
		if err != nil {
			report := a.Shutdown(ctx)
			return nil, errors.Join(err, report)
		}
	}
	{
		start := time.Now()
		err := a.migrator.Init(ctx)
		a.startupReport.Nodes = append(a.startupReport.Nodes, servo.StartupNode{Type: "*example.com/servobasic/migrator.Migrator", Duration: time.Since(start)})
		if err != nil {
			report := a.Shutdown(ctx)
			return nil, errors.Join(err, report)
		}
	}
	return a, nil
}

func (a *App) stopLogger(ctx context.Context) servo.NodeResult {
	a.loggerStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servobasic/logger.Logger", a.logger.Stop))
		a.loggerStopResult = servo.MergeNodeResults("*example.com/servobasic/logger.Logger", results...)
	})
	return a.loggerStopResult
}

func (a *App) stopDb(ctx context.Context) servo.NodeResult {
	a.dbStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servobasic/postgres.DB", a.db.Stop))
		a.dbStopResult = servo.MergeNodeResults("*example.com/servobasic/postgres.DB", results...)
	})
	return a.dbStopResult
}

func (a *App) Run(ctx context.Context) error {
	return nil
}

func (a *App) Shutdown(ctx context.Context) servo.Report {
	forceExit := make(chan os.Signal, 1)
	signal.Notify(forceExit, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(forceExit)
	watcherDone := make(chan struct{})
	defer close(watcherDone)
	go func() {
		select {
		case <-forceExit:
			os.Exit(1)
		case <-watcherDone:
		}
	}()

	var nodes []servo.NodeResult
	nodes = append(nodes, a.stopDb(ctx))
	nodes = append(nodes, a.stopLogger(ctx))
	return servo.Report{Nodes: nodes}
}

func (a *App) Health(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	if err := a.db.Health(ctx); err != nil {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servobasic/postgres.DB", Status: servo.StatusFailed, Err: err})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servobasic/postgres.DB", Status: servo.StatusOK})
	}
	return servo.Report{Nodes: nodes}
}

func (a *App) Ready(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Graph() servo.Graph {
	return servo.Graph{Nodes: []servo.GraphNode{
		{Type: "*example.com/servobasic/logger.Logger", Level: 1, Deps: nil, Capabilities: []string{"Finalizer"}, Binding: "sole candidate", Pos: "logger/logger.go:10:6"},
		{Type: "*example.com/servobasic/postgres.DB", Level: 2, Deps: []string{"*example.com/servobasic/logger.Logger"}, Capabilities: []string{"Initializer", "Finalizer", "Healther"}, Binding: "sole candidate", Pos: "postgres/postgres.go:13:6"},
		{Type: "*example.com/servobasic/migrator.Migrator", Level: 3, Deps: []string{"*example.com/servobasic/postgres.DB", "*example.com/servobasic/logger.Logger"}, Capabilities: []string{"Initializer"}, Binding: "sole candidate", Pos: "migrator/migrator.go:15:6"},
	}}
}

func (a *App) Report() servo.StartupReport {
	return a.startupReport
}
