//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// ServoConfig fills config from the process environment.
// Settings:
//
//	REDIS_ADDR string, required
package redis

import (
	"fmt"
	"os"
	"strings"
)

// ServoConfig builds config. Precedence per setting: default, then the REDIS_* environment
// variable — the environment always wins.
func ServoConfig() (config, error) {
	var cfg config
	var missing []string

	// addr — REDIS_ADDR (required)
	if v, ok := os.LookupEnv("REDIS_ADDR"); ok {
		cfg.addr = v
	} else {
		missing = append(missing, "REDIS_ADDR")
	}

	if len(missing) > 0 {
		return config{}, fmt.Errorf("redis: missing required configuration: %s", strings.Join(missing, ", "))
	}
	return cfg, nil
}
