//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// Resolved graph:
//
//	[L1] *example.com/servoorders/config.Config
//	      deps: none
//	      capabilities: none | binding: sole candidate | config/config.go:39:6
//	[L1] *example.com/servoorders/mocks.OrderRepositoryForServo
//	      deps: none
//	      capabilities: none | binding: explicit bind | mocks/servo_adapters.go:24:6
//	[L1] *example.com/servoorders/mocks.OrderCacheForServo
//	      deps: none
//	      capabilities: none | binding: explicit bind | mocks/servo_adapters.go:44:6
//	[L1] *example.com/servoorders/mocks.EventPublisherForServo
//	      deps: none
//	      capabilities: none | binding: explicit bind | mocks/servo_adapters.go:54:6
//	[L2] *example.com/servoorders/service.OrderService
//	      deps: *example.com/servoorders/mocks.OrderRepositoryForServo, *example.com/servoorders/mocks.OrderCacheForServo, *example.com/servoorders/mocks.EventPublisherForServo
//	      capabilities: none | binding: sole candidate | service/service.go:27:6
//	[L1] *example.com/servoorders/mocks.UserRepositoryForServo
//	      deps: none
//	      capabilities: none | binding: explicit bind | mocks/servo_adapters.go:34:6
//	[L2] *example.com/servoorders/auth.Issuer
//	      deps: *example.com/servoorders/config.Config
//	      capabilities: none | binding: sole candidate | auth/auth.go:28:6
//	[L3] *example.com/servoorders/service.AuthService
//	      deps: *example.com/servoorders/mocks.UserRepositoryForServo, *example.com/servoorders/auth.Issuer
//	      capabilities: none | binding: sole candidate | service/auth_service.go:18:6
//	[L1] *example.com/servoorders/observability.Metrics
//	      deps: none
//	      capabilities: none | binding: sole candidate | observability/metrics.go:18:6
//	[L2] *example.com/servoorders/observability.Tracer
//	      deps: *example.com/servoorders/config.Config
//	      capabilities: Finalizer | binding: sole candidate | observability/tracing.go:30:6
//	[L2] *example.com/servoorders/resilience.RateLimiter
//	      deps: *example.com/servoorders/config.Config, *example.com/servoorders/observability.Metrics
//	      capabilities: none | binding: sole candidate | resilience/ratelimit.go:23:6
//	[L4] *example.com/servoorders/api.Server
//	      deps: *example.com/servoorders/config.Config, *example.com/servoorders/service.OrderService, *example.com/servoorders/service.AuthService, *example.com/servoorders/auth.Issuer, *example.com/servoorders/observability.Metrics, *example.com/servoorders/observability.Tracer, *example.com/servoorders/resilience.RateLimiter
//	      capabilities: Runner, Finalizer | binding: sole candidate | api/server.go:26:6
//	[L2] *example.com/servoorders/notifier.Notifier
//	      deps: *example.com/servoorders/config.Config
//	      capabilities: Runner | binding: sole candidate | notifier/notifier.go:23:6
package main

import (
	"context"
	"example.com/servoorders/api"
	"example.com/servoorders/auth"
	"example.com/servoorders/config"
	"example.com/servoorders/mocks"
	"example.com/servoorders/notifier"
	"example.com/servoorders/observability"
	"example.com/servoorders/resilience"
	"example.com/servoorders/service"
	"github.com/okian/servo/v3/servo"
	"golang.org/x/sync/errgroup"
	"os"
	"os/signal"
	"sync"
	"syscall"
)

type TestApp struct {
	config                  *config.Config
	orderRepositoryForServo *mocks.OrderRepositoryForServo
	orderCacheForServo      *mocks.OrderCacheForServo
	eventPublisherForServo  *mocks.EventPublisherForServo
	orderService            *service.OrderService
	userRepositoryForServo  *mocks.UserRepositoryForServo
	issuer                  *auth.Issuer
	authService             *service.AuthService
	metrics                 *observability.Metrics
	tracer                  *observability.Tracer
	tracerStopOnce          sync.Once
	tracerStopResult        servo.NodeResult
	rateLimiter             *resilience.RateLimiter
	server                  *api.Server
	serverStopOnce          sync.Once
	serverStopResult        servo.NodeResult
	notifier                *notifier.Notifier
	startupReport           servo.StartupReport
}

func NewTestApp(ctx context.Context) (*TestApp, error) {
	a := &TestApp{}

	config, err := config.New()
	if err != nil {
		return nil, err
	}
	a.config = config

	orderRepositoryForServo := mocks.NewOrderRepositoryForServo()
	a.orderRepositoryForServo = orderRepositoryForServo

	orderCacheForServo := mocks.NewOrderCacheForServo()
	a.orderCacheForServo = orderCacheForServo

	eventPublisherForServo := mocks.NewEventPublisherForServo()
	a.eventPublisherForServo = eventPublisherForServo

	orderService := service.New(orderRepositoryForServo, orderCacheForServo, eventPublisherForServo)
	a.orderService = orderService

	userRepositoryForServo := mocks.NewUserRepositoryForServo()
	a.userRepositoryForServo = userRepositoryForServo

	issuer := auth.New(config)
	a.issuer = issuer

	authService := service.NewAuthService(userRepositoryForServo, issuer)
	a.authService = authService

	metrics := observability.NewMetrics()
	a.metrics = metrics

	tracer, err := observability.NewTracer(config)
	if err != nil {
		return nil, err
	}
	a.tracer = tracer

	rateLimiter := resilience.NewRateLimiter(config, metrics)
	a.rateLimiter = rateLimiter

	server := api.New(config, orderService, authService, issuer, metrics, tracer, rateLimiter)
	a.server = server

	notifier := notifier.New(config)
	a.notifier = notifier

	return a, nil
}

func (a *TestApp) stopTracer(ctx context.Context) servo.NodeResult {
	a.tracerStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoorders/observability.Tracer", a.tracer.Stop))
		a.tracerStopResult = servo.MergeNodeResults("*example.com/servoorders/observability.Tracer", results...)
	})
	return a.tracerStopResult
}

func (a *TestApp) stopServer(ctx context.Context) servo.NodeResult {
	a.serverStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoorders/api.Server", a.server.Stop))
		a.serverStopResult = servo.MergeNodeResults("*example.com/servoorders/api.Server", results...)
	})
	return a.serverStopResult
}

func (a *TestApp) Run(ctx context.Context) error {
	g, gctx := errgroup.WithContext(ctx)
	g.Go(func() error { return a.server.Run(gctx) })
	g.Go(func() error { return a.notifier.Run(gctx) })
	return g.Wait()
}

func (a *TestApp) Shutdown(ctx context.Context) servo.Report {
	forceExit := make(chan os.Signal, 1)
	signal.Notify(forceExit, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(forceExit)
	watcherDone := make(chan struct{})
	defer close(watcherDone)
	go func() {
		select {
		case <-forceExit:
			os.Exit(1)
		case <-watcherDone:
		}
	}()

	var nodes []servo.NodeResult
	nodes = append(nodes, a.stopServer(ctx))
	nodes = append(nodes, a.stopTracer(ctx))
	return servo.Report{Nodes: nodes}
}

func (a *TestApp) Health(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *TestApp) Ready(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *TestApp) Graph() servo.Graph {
	return servo.Graph{Nodes: []servo.GraphNode{
		{Type: "*example.com/servoorders/config.Config", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "config/config.go:39:6"},
		{Type: "*example.com/servoorders/mocks.OrderRepositoryForServo", Level: 1, Deps: nil, Capabilities: nil, Binding: "explicit bind", Pos: "mocks/servo_adapters.go:24:6"},
		{Type: "*example.com/servoorders/mocks.OrderCacheForServo", Level: 1, Deps: nil, Capabilities: nil, Binding: "explicit bind", Pos: "mocks/servo_adapters.go:44:6"},
		{Type: "*example.com/servoorders/mocks.EventPublisherForServo", Level: 1, Deps: nil, Capabilities: nil, Binding: "explicit bind", Pos: "mocks/servo_adapters.go:54:6"},
		{Type: "*example.com/servoorders/service.OrderService", Level: 2, Deps: []string{"*example.com/servoorders/mocks.OrderRepositoryForServo", "*example.com/servoorders/mocks.OrderCacheForServo", "*example.com/servoorders/mocks.EventPublisherForServo"}, Capabilities: nil, Binding: "sole candidate", Pos: "service/service.go:27:6"},
		{Type: "*example.com/servoorders/mocks.UserRepositoryForServo", Level: 1, Deps: nil, Capabilities: nil, Binding: "explicit bind", Pos: "mocks/servo_adapters.go:34:6"},
		{Type: "*example.com/servoorders/auth.Issuer", Level: 2, Deps: []string{"*example.com/servoorders/config.Config"}, Capabilities: nil, Binding: "sole candidate", Pos: "auth/auth.go:28:6"},
		{Type: "*example.com/servoorders/service.AuthService", Level: 3, Deps: []string{"*example.com/servoorders/mocks.UserRepositoryForServo", "*example.com/servoorders/auth.Issuer"}, Capabilities: nil, Binding: "sole candidate", Pos: "service/auth_service.go:18:6"},
		{Type: "*example.com/servoorders/observability.Metrics", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "observability/metrics.go:18:6"},
		{Type: "*example.com/servoorders/observability.Tracer", Level: 2, Deps: []string{"*example.com/servoorders/config.Config"}, Capabilities: []string{"Finalizer"}, Binding: "sole candidate", Pos: "observability/tracing.go:30:6"},
		{Type: "*example.com/servoorders/resilience.RateLimiter", Level: 2, Deps: []string{"*example.com/servoorders/config.Config", "*example.com/servoorders/observability.Metrics"}, Capabilities: nil, Binding: "sole candidate", Pos: "resilience/ratelimit.go:23:6"},
		{Type: "*example.com/servoorders/api.Server", Level: 4, Deps: []string{"*example.com/servoorders/config.Config", "*example.com/servoorders/service.OrderService", "*example.com/servoorders/service.AuthService", "*example.com/servoorders/auth.Issuer", "*example.com/servoorders/observability.Metrics", "*example.com/servoorders/observability.Tracer", "*example.com/servoorders/resilience.RateLimiter"}, Capabilities: []string{"Runner", "Finalizer"}, Binding: "sole candidate", Pos: "api/server.go:26:6"},
		{Type: "*example.com/servoorders/notifier.Notifier", Level: 2, Deps: []string{"*example.com/servoorders/config.Config"}, Capabilities: []string{"Runner"}, Binding: "sole candidate", Pos: "notifier/notifier.go:23:6"},
	}}
}

func (a *TestApp) Report() servo.StartupReport {
	return a.startupReport
}
