//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// Resolved graph:
//
//	[L1] *example.com/servoorders/config.Config
//	      deps: none
//	      capabilities: none | binding: sole candidate | config/config.go:39:6
//	[L2] *example.com/servoorders/postgres.Store
//	      deps: *example.com/servoorders/config.Config
//	      capabilities: Initializer, Finalizer, Healther | binding: explicit bind | postgres/postgres.go:31:6
//	[L2] *example.com/servoorders/redis.Cache
//	      deps: *example.com/servoorders/config.Config
//	      capabilities: Initializer, Finalizer, Healther | binding: explicit bind | redis/redis.go:30:6
//	[L2] *example.com/servoorders/natsbroker.Publisher
//	      deps: *example.com/servoorders/config.Config
//	      capabilities: Initializer, Finalizer, Healther | binding: explicit bind | natsbroker/natsbroker.go:26:6
//	[L3] *example.com/servoorders/service.OrderService
//	      deps: *example.com/servoorders/postgres.Store, *example.com/servoorders/redis.Cache, *example.com/servoorders/natsbroker.Publisher
//	      capabilities: none | binding: sole candidate | service/service.go:27:6
//	[L2] *example.com/servoorders/auth.Issuer
//	      deps: *example.com/servoorders/config.Config
//	      capabilities: none | binding: sole candidate | auth/auth.go:28:6
//	[L3] *example.com/servoorders/service.AuthService
//	      deps: *example.com/servoorders/postgres.Store, *example.com/servoorders/auth.Issuer
//	      capabilities: none | binding: sole candidate | service/auth_service.go:18:6
//	[L4] *example.com/servoorders/api.Server
//	      deps: *example.com/servoorders/config.Config, *example.com/servoorders/service.OrderService, *example.com/servoorders/service.AuthService, *example.com/servoorders/auth.Issuer
//	      capabilities: Runner, Finalizer | binding: sole candidate | api/server.go:23:6
//	[L2] *example.com/servoorders/notifier.Notifier
//	      deps: *example.com/servoorders/config.Config
//	      capabilities: Runner | binding: sole candidate | notifier/notifier.go:23:6
package main

import (
	"context"
	"errors"
	"example.com/servoorders/api"
	"example.com/servoorders/auth"
	"example.com/servoorders/config"
	"example.com/servoorders/natsbroker"
	"example.com/servoorders/notifier"
	"example.com/servoorders/postgres"
	"example.com/servoorders/redis"
	"example.com/servoorders/service"
	"github.com/okian/servo/v3/servo"
	"golang.org/x/sync/errgroup"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"
)

type App struct {
	config              *config.Config
	store               *postgres.Store
	storeStopOnce       sync.Once
	storeStopResult     servo.NodeResult
	cache               *redis.Cache
	cacheStopOnce       sync.Once
	cacheStopResult     servo.NodeResult
	publisher           *natsbroker.Publisher
	publisherStopOnce   sync.Once
	publisherStopResult servo.NodeResult
	orderService        *service.OrderService
	issuer              *auth.Issuer
	authService         *service.AuthService
	server              *api.Server
	serverStopOnce      sync.Once
	serverStopResult    servo.NodeResult
	notifier            *notifier.Notifier
	startupReport       servo.StartupReport
}

func New(ctx context.Context) (*App, error) {
	a := &App{}

	config, err := config.New()
	if err != nil {
		return nil, err
	}
	a.config = config

	store, err := postgres.New(config)
	if err != nil {
		return nil, err
	}
	a.store = store

	cache := redis.New(config)
	a.cache = cache

	publisher := natsbroker.New(config)
	a.publisher = publisher

	orderService := service.New(store, cache, publisher)
	a.orderService = orderService

	issuer := auth.New(config)
	a.issuer = issuer

	authService := service.NewAuthService(store, issuer)
	a.authService = authService

	server := api.New(config, orderService, authService, issuer)
	a.server = server

	notifier := notifier.New(config)
	a.notifier = notifier

	{
		var timingMu sync.Mutex
		g, gctx := errgroup.WithContext(ctx)
		g.Go(func() error {
			start := time.Now()
			err := a.store.Init(gctx)
			timingMu.Lock()
			a.startupReport.Nodes = append(a.startupReport.Nodes, servo.StartupNode{Type: "*example.com/servoorders/postgres.Store", Duration: time.Since(start)})
			timingMu.Unlock()
			return err
		})
		g.Go(func() error {
			start := time.Now()
			err := a.cache.Init(gctx)
			timingMu.Lock()
			a.startupReport.Nodes = append(a.startupReport.Nodes, servo.StartupNode{Type: "*example.com/servoorders/redis.Cache", Duration: time.Since(start)})
			timingMu.Unlock()
			return err
		})
		g.Go(func() error {
			start := time.Now()
			err := a.publisher.Init(gctx)
			timingMu.Lock()
			a.startupReport.Nodes = append(a.startupReport.Nodes, servo.StartupNode{Type: "*example.com/servoorders/natsbroker.Publisher", Duration: time.Since(start)})
			timingMu.Unlock()
			return err
		})
		if err := g.Wait(); err != nil {
			report := a.Shutdown(ctx)
			return nil, errors.Join(err, report)
		}
	}
	return a, nil
}

func (a *App) stopStore(ctx context.Context) servo.NodeResult {
	a.storeStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoorders/postgres.Store", a.store.Stop))
		a.storeStopResult = servo.MergeNodeResults("*example.com/servoorders/postgres.Store", results...)
	})
	return a.storeStopResult
}

func (a *App) stopCache(ctx context.Context) servo.NodeResult {
	a.cacheStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoorders/redis.Cache", a.cache.Stop))
		a.cacheStopResult = servo.MergeNodeResults("*example.com/servoorders/redis.Cache", results...)
	})
	return a.cacheStopResult
}

func (a *App) stopPublisher(ctx context.Context) servo.NodeResult {
	a.publisherStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoorders/natsbroker.Publisher", a.publisher.Stop))
		a.publisherStopResult = servo.MergeNodeResults("*example.com/servoorders/natsbroker.Publisher", results...)
	})
	return a.publisherStopResult
}

func (a *App) stopServer(ctx context.Context) servo.NodeResult {
	a.serverStopOnce.Do(func() {
		var results []servo.NodeResult
		results = append(results, servo.RunStop(ctx, servo.DefaultStopBudget, "*example.com/servoorders/api.Server", a.server.Stop))
		a.serverStopResult = servo.MergeNodeResults("*example.com/servoorders/api.Server", results...)
	})
	return a.serverStopResult
}

func (a *App) Run(ctx context.Context) error {
	g, gctx := errgroup.WithContext(ctx)
	g.Go(func() error { return a.server.Run(gctx) })
	g.Go(func() error { return a.notifier.Run(gctx) })
	return g.Wait()
}

func (a *App) Shutdown(ctx context.Context) servo.Report {
	forceExit := make(chan os.Signal, 1)
	signal.Notify(forceExit, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(forceExit)
	watcherDone := make(chan struct{})
	defer close(watcherDone)
	go func() {
		select {
		case <-forceExit:
			os.Exit(1)
		case <-watcherDone:
		}
	}()

	var nodes []servo.NodeResult
	nodes = append(nodes, a.stopServer(ctx))
	nodes = append(nodes, a.stopPublisher(ctx))
	nodes = append(nodes, a.stopCache(ctx))
	nodes = append(nodes, a.stopStore(ctx))
	return servo.Report{Nodes: nodes}
}

func (a *App) Health(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	if err := a.store.Health(ctx); err != nil {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servoorders/postgres.Store", Status: servo.StatusFailed, Err: err})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servoorders/postgres.Store", Status: servo.StatusOK})
	}
	if err := a.cache.Health(ctx); err != nil {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servoorders/redis.Cache", Status: servo.StatusFailed, Err: err})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servoorders/redis.Cache", Status: servo.StatusOK})
	}
	if err := a.publisher.Health(ctx); err != nil {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servoorders/natsbroker.Publisher", Status: servo.StatusFailed, Err: err})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "*example.com/servoorders/natsbroker.Publisher", Status: servo.StatusOK})
	}
	return servo.Report{Nodes: nodes}
}

func (a *App) Ready(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Graph() servo.Graph {
	return servo.Graph{Nodes: []servo.GraphNode{
		{Type: "*example.com/servoorders/config.Config", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "config/config.go:39:6"},
		{Type: "*example.com/servoorders/postgres.Store", Level: 2, Deps: []string{"*example.com/servoorders/config.Config"}, Capabilities: []string{"Initializer", "Finalizer", "Healther"}, Binding: "explicit bind", Pos: "postgres/postgres.go:31:6"},
		{Type: "*example.com/servoorders/redis.Cache", Level: 2, Deps: []string{"*example.com/servoorders/config.Config"}, Capabilities: []string{"Initializer", "Finalizer", "Healther"}, Binding: "explicit bind", Pos: "redis/redis.go:30:6"},
		{Type: "*example.com/servoorders/natsbroker.Publisher", Level: 2, Deps: []string{"*example.com/servoorders/config.Config"}, Capabilities: []string{"Initializer", "Finalizer", "Healther"}, Binding: "explicit bind", Pos: "natsbroker/natsbroker.go:26:6"},
		{Type: "*example.com/servoorders/service.OrderService", Level: 3, Deps: []string{"*example.com/servoorders/postgres.Store", "*example.com/servoorders/redis.Cache", "*example.com/servoorders/natsbroker.Publisher"}, Capabilities: nil, Binding: "sole candidate", Pos: "service/service.go:27:6"},
		{Type: "*example.com/servoorders/auth.Issuer", Level: 2, Deps: []string{"*example.com/servoorders/config.Config"}, Capabilities: nil, Binding: "sole candidate", Pos: "auth/auth.go:28:6"},
		{Type: "*example.com/servoorders/service.AuthService", Level: 3, Deps: []string{"*example.com/servoorders/postgres.Store", "*example.com/servoorders/auth.Issuer"}, Capabilities: nil, Binding: "sole candidate", Pos: "service/auth_service.go:18:6"},
		{Type: "*example.com/servoorders/api.Server", Level: 4, Deps: []string{"*example.com/servoorders/config.Config", "*example.com/servoorders/service.OrderService", "*example.com/servoorders/service.AuthService", "*example.com/servoorders/auth.Issuer"}, Capabilities: []string{"Runner", "Finalizer"}, Binding: "sole candidate", Pos: "api/server.go:23:6"},
		{Type: "*example.com/servoorders/notifier.Notifier", Level: 2, Deps: []string{"*example.com/servoorders/config.Config"}, Capabilities: []string{"Runner"}, Binding: "sole candidate", Pos: "notifier/notifier.go:23:6"},
	}}
}

func (a *App) Report() servo.StartupReport {
	return a.startupReport
}
