//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// ServoConfig fills Config from the process environment.
// Settings:
//
//	HTTP_ADDR       string, default :8080
//	HTTP_ADMIN_ADDR string, default :8081
package grpcapi

import (
	"os"
)

// ServoConfig builds Config. Precedence per setting: default, then the HTTP_* environment
// variable — the environment always wins.
func ServoConfig() (Config, error) {
	var cfg Config

	// addr — HTTP_ADDR
	cfg.HTTPAddr = ":8080"
	if v, ok := os.LookupEnv("HTTP_ADDR"); ok {
		cfg.HTTPAddr = v
	}

	// admin_addr — HTTP_ADMIN_ADDR
	cfg.AdminAddr = ":8081"
	if v, ok := os.LookupEnv("HTTP_ADMIN_ADDR"); ok {
		cfg.AdminAddr = v
	}
	return cfg, nil
}
