//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// ServoConfig fills Config from the process environment.
// Settings:
//
//	JWT_SECRET string, required, secret
//	JWT_EXPIRY time.Duration, default 1h
package auth

import (
	"fmt"
	"os"
	"strings"
	"time"
)

// ServoConfig builds Config. Precedence per setting: default, then the JWT_* environment
// variable — the environment always wins.
func ServoConfig() (Config, error) {
	var cfg Config
	var missing []string

	// secret — JWT_SECRET (required)
	if v, ok := os.LookupEnv("JWT_SECRET"); ok {
		cfg.Secret = v
	} else {
		missing = append(missing, "JWT_SECRET")
	}

	// expiry — JWT_EXPIRY
	cfg.Expiry = time.Hour
	if v, ok := os.LookupEnv("JWT_EXPIRY"); ok {
		val, err := time.ParseDuration(v)
		if err != nil {
			return Config{}, fmt.Errorf("JWT_EXPIRY: not a valid time.Duration: %q", v)
		}
		cfg.Expiry = val
	}

	if len(missing) > 0 {
		return Config{}, fmt.Errorf("auth: missing required configuration: %s", strings.Join(missing, ", "))
	}
	return cfg, nil
}
