//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// Resolved graph:
//
//	[L1] *example.com/servomocking/gomock/mockgenstore.MockStoreForServo
//	      deps: none
//	      capabilities: none | binding: explicit bind | gomock/mockgenstore/adapter.go:22:6
//	[L2] *example.com/servomocking/api.Server
//	      deps: *example.com/servomocking/gomock/mockgenstore.MockStoreForServo
//	      capabilities: none | binding: sole candidate | api/api.go:7:6
package main

import (
	"context"
	"example.com/servomocking/api"
	"example.com/servomocking/gomock/mockgenstore"
	"github.com/okian/servo/v2/servo"
	"os"
	"os/signal"
	"syscall"
)

type TestApp struct {
	mockStoreForServo *mockgenstore.MockStoreForServo
	server            *api.Server
	startupReport     servo.StartupReport
}

func NewTestApp(ctx context.Context) (*TestApp, error) {
	a := &TestApp{}

	mockStoreForServo := mockgenstore.NewMockStoreForServo()
	a.mockStoreForServo = mockStoreForServo

	server := api.New(mockStoreForServo)
	a.server = server

	return a, nil
}

func (a *TestApp) Run(ctx context.Context) error {
	return nil
}

func (a *TestApp) Shutdown(ctx context.Context) servo.Report {
	forceExit := make(chan os.Signal, 1)
	signal.Notify(forceExit, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(forceExit)
	watcherDone := make(chan struct{})
	defer close(watcherDone)
	go func() {
		select {
		case <-forceExit:
			os.Exit(1)
		case <-watcherDone:
		}
	}()

	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *TestApp) Health(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *TestApp) Ready(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *TestApp) Graph() servo.Graph {
	return servo.Graph{Nodes: []servo.GraphNode{
		{Type: "*example.com/servomocking/gomock/mockgenstore.MockStoreForServo", Level: 1, Deps: nil, Capabilities: nil, Binding: "explicit bind", Pos: "gomock/mockgenstore/adapter.go:22:6"},
		{Type: "*example.com/servomocking/api.Server", Level: 2, Deps: []string{"*example.com/servomocking/gomock/mockgenstore.MockStoreForServo"}, Capabilities: nil, Binding: "sole candidate", Pos: "api/api.go:7:6"},
	}}
}

func (a *TestApp) Report() servo.StartupReport {
	return a.startupReport
}
