//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// Resolved graph:
//
//	[L1] *github.com/okian/servo/v3/servo.HTTPConfig
//	      deps: none
//	      capabilities: none | binding: sole candidate | api/api.go:38:6
//	[L1] *example.com/servohttp/mw.UserExtractor
//	      deps: none
//	      capabilities: none | binding: sole candidate | mw/mw.go:35:6
//	[L1] *github.com/okian/servo/v3/middleware.Recover
//	      deps: none
//	      capabilities: none | binding: sole candidate | /Users/kian/servo/middleware/recover.go:17:6
//	[L1] *github.com/okian/servo/v3/middleware.RequestID
//	      deps: none
//	      capabilities: none | binding: sole candidate | /Users/kian/servo/middleware/requestid.go:17:6
//	[L1] *github.com/okian/servo/v3/middleware.CORSConfig
//	      deps: none
//	      capabilities: none | binding: sole candidate | api/api.go:25:6
//	[L2] *github.com/okian/servo/v3/middleware.CORS
//	      deps: *github.com/okian/servo/v3/middleware.CORSConfig
//	      capabilities: none | binding: sole candidate | /Users/kian/servo/middleware/cors.go:44:6
//	[L1] *example.com/servohttp/mw.Auth
//	      deps: none
//	      capabilities: none | binding: sole candidate | mw/mw.go:17:6
//	[L1] *example.com/servohttp/store.Store
//	      deps: none
//	      capabilities: none | binding: sole candidate | store/store.go:22:6
//
// http (servo.HTTP() at cmd/app/spec.go:23:3):
//
//	config: *github.com/okian/servo/v3/servo.HTTPConfig
//	groups: internal, telemetry
//	use: *github.com/okian/servo/v3/middleware.Recover -> every group
//	use: *github.com/okian/servo/v3/middleware.RequestID -> every group
//	use: *github.com/okian/servo/v3/middleware.CORS -> group default
//	use: *example.com/servohttp/mw.Auth -> group internal
//	extract: *example.com/servohttp/mw.UserExtractor -> *example.com/servohttp/mw.User
//	POST /feedback -> api.Feedback (api/api.go:193:1)
//	      args: none
//	GET /old-orders -> api.OldOrders (api/api.go:208:1)
//	      args: none
//	POST /order/{category}/ -> api.Order (api/api.go:94:1)
//	      args: *example.com/servohttp/store.Store
//	GET /search -> api.Search (api/api.go:131:1)
//	      args: none
//	GET /version -> api.Version (api/api.go:200:1)
//	      args: none
//	GET /whoami -> api.Whoami (api/api.go:145:1)
//	      args: *example.com/servohttp/mw.User (extracted)
//	POST /replicate/{shard} [internal] -> api.Replicate (api/api.go:175:1)
//	      args: *example.com/servohttp/mw.User (extracted)
//	GET /healthz [telemetry] -> api.Healthz (api/api.go:158:1)
//	      args: none
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"sync"
	"sync/atomic"
	"syscall"

	"example.com/servohttp/api"
	"example.com/servohttp/mw"
	"example.com/servohttp/store"
	"github.com/okian/servo/v3/middleware"
	"github.com/okian/servo/v3/servo"
	"golang.org/x/sync/errgroup"
)

type App struct {
	hTTPConfig                    *servo.HTTPConfig
	userExtractor                 *mw.UserExtractor
	recover2                      *middleware.Recover
	requestID                     *middleware.RequestID
	cORSConfig                    *middleware.CORSConfig
	cors                          *middleware.CORS
	auth                          *mw.Auth
	store                         *store.Store
	httpServer                    *httpServer
	httpServerStopOnce            sync.Once
	httpServerStopResult          servo.NodeResult
	httpInternalServer            *httpInternalServer
	httpInternalServerStopOnce    sync.Once
	httpInternalServerStopResult  servo.NodeResult
	httpTelemetryServer           *httpTelemetryServer
	httpTelemetryServerStopOnce   sync.Once
	httpTelemetryServerStopResult servo.NodeResult
	startupReport                 servo.StartupReport
}

const defaultMaxBodyBytes = 1 << 20

// httpServer serves the default group's //servo: routes. It is generated
// machinery, not a graph node: its dependencies are ordinary singletons
// on the App, resolved once at construction.
type httpServer struct {
	app     *App
	lc      servo.HTTPListener
	srv     *http.Server
	maxBody int64
	// ready flips once the listener is bound, which is the precise moment
	// Ready starts reporting ok for the "http" node.
	ready atomic.Bool
}

func newHttpServer(a *App) (*httpServer, error) {
	cfg := a.hTTPConfig
	lc := servo.HTTPListener{
		IP:           cfg.IP,
		Port:         cfg.Port,
		CertFile:     cfg.CertFile,
		KeyFile:      cfg.KeyFile,
		MaxBodyBytes: cfg.MaxBodyBytes,
		ReadTimeout:  cfg.ReadTimeout,
		WriteTimeout: cfg.WriteTimeout,
		IdleTimeout:  cfg.IdleTimeout,
	}
	s := &httpServer{app: a, lc: lc}
	s.maxBody = lc.MaxBodyBytes
	if s.maxBody <= 0 {
		s.maxBody = defaultMaxBodyBytes
	}
	mux := http.NewServeMux()
	mux.HandleFunc("POST /feedback", s.handleFeedback)
	mux.HandleFunc("GET /old-orders", s.handleOldOrders)
	mux.HandleFunc("POST /order/{category}/", s.handleOrder)
	mux.HandleFunc("GET /search", s.handleSearch)
	mux.HandleFunc("GET /version", s.handleVersion)
	mux.HandleFunc("GET /whoami", s.handleWhoami)
	var handler http.Handler = mux
	handler = a.cors.Middleware(handler)
	handler = a.requestID.Middleware(handler)
	handler = a.recover2.Middleware(handler)
	s.srv = &http.Server{
		Addr:         net.JoinHostPort(lc.IP, strconv.FormatUint(uint64(lc.Port), 10)),
		Handler:      handler,
		ReadTimeout:  lc.ReadTimeout,
		WriteTimeout: lc.WriteTimeout,
		IdleTimeout:  lc.IdleTimeout,
	}
	return s, nil
}

func (s *httpServer) handleFeedback(w http.ResponseWriter, r *http.Request) {
	req := &api.FeedbackReq{}
	r.Body = http.MaxBytesReader(w, r.Body, s.maxBody)
	// ParseMultipartForm falls through to ParseForm on urlencoded
	// bodies, reporting ErrNotMultipart after already parsing them.
	if err := r.ParseMultipartForm(s.maxBody); err != nil && !errors.Is(err, http.ErrNotMultipart) {
		httpWriteError(w, http.StatusBadRequest, "malformed form body")
		return
	}
	req.Subject = r.PostForm.Get("subject")
	if raw := r.PostForm.Get("stars"); raw != "" {
		v, err := strconv.ParseInt(raw, 10, 0)
		if err != nil {
			httpWriteError(w, http.StatusBadRequest, "form value \"stars\" is not a valid int")
			return
		}
		req.Stars = int(v)
	}
	res, err := api.Feedback(r.Context(), req)
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "api.Feedback", "POST /feedback", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpServer) handleOldOrders(w http.ResponseWriter, r *http.Request) {
	res, err := api.OldOrders(r.Context())
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "api.OldOrders", "GET /old-orders", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpServer) handleOrder(w http.ResponseWriter, r *http.Request) {
	req := &api.OrderReq{}
	// The body decodes first, so the explicitly bound sources below
	// overwrite anything it could smuggle into a same-named field.
	r.Body = http.MaxBytesReader(w, r.Body, s.maxBody)
	if err := json.NewDecoder(r.Body).Decode(req); err != nil {
		httpWriteError(w, http.StatusBadRequest, "malformed request body")
		return
	}
	q := r.URL.Query()
	req.Category = r.PathValue("category")
	if raw := q.Get("priority"); raw != "" {
		v, err := strconv.ParseInt(raw, 10, 0)
		if err != nil {
			httpWriteError(w, http.StatusBadRequest, "query parameter \"priority\" is not a valid int")
			return
		}
		req.Priority = int(v)
	}
	res, err := api.Order(r.Context(), req, s.app.store)
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "api.Order", "POST /order/{category}/", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpServer) handleSearch(w http.ResponseWriter, r *http.Request) {
	req := &api.SearchReq{}
	q := r.URL.Query()
	req.Q = q.Get("q")
	if raw := q.Get("limit"); raw != "" {
		v, err := strconv.ParseUint(raw, 10, 16)
		if err != nil {
			httpWriteError(w, http.StatusBadRequest, "query parameter \"limit\" is not a valid uint16")
			return
		}
		req.Limit = uint16(v)
	}
	if raw := q.Get("ratio"); raw != "" {
		v, err := strconv.ParseFloat(raw, 64)
		if err != nil {
			httpWriteError(w, http.StatusBadRequest, "query parameter \"ratio\" is not a valid float64")
			return
		}
		req.Ratio = v
	}
	if raw := q.Get("exact"); raw != "" {
		v, err := strconv.ParseBool(raw)
		if err != nil {
			httpWriteError(w, http.StatusBadRequest, "query parameter \"exact\" is not a valid bool")
			return
		}
		req.Exact = v
	}
	res, err := api.Search(r.Context(), req)
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "api.Search", "GET /search", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpServer) handleVersion(w http.ResponseWriter, r *http.Request) {
	res, err := api.Version(r.Context())
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "api.Version", "GET /version", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpServer) handleWhoami(w http.ResponseWriter, r *http.Request) {
	user, err := s.app.userExtractor.Extract(r)
	if err != nil {
		httpWriteFailure(w, "api.Whoami", "GET /whoami", err)
		return
	}
	res, err := api.Whoami(r.Context(), user)
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "api.Whoami", "GET /whoami", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpServer) run(ctx context.Context) error {
	ln, err := net.Listen("tcp", s.srv.Addr)
	if err != nil {
		return fmt.Errorf("http: listen %s: %w", s.srv.Addr, err)
	}
	s.ready.Store(true)
	serveErr := make(chan error, 1)
	go func() {
		var err error
		if s.lc.CertFile != "" && s.lc.KeyFile != "" {
			err = s.srv.ServeTLS(ln, s.lc.CertFile, s.lc.KeyFile)
		} else {
			err = s.srv.Serve(ln)
		}
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			serveErr <- err
			return
		}
		serveErr <- nil
	}()
	select {
	case <-ctx.Done():
		return nil
	case err := <-serveErr:
		return err
	}
}

// httpInternalServer serves group "internal"'s //servo: routes. It is generated
// machinery, not a graph node: its dependencies are ordinary singletons
// on the App, resolved once at construction.
type httpInternalServer struct {
	app *App
	lc  servo.HTTPListener
	srv *http.Server
	// ready flips once the listener is bound, which is the precise moment
	// Ready starts reporting ok for the "http:internal" node.
	ready atomic.Bool
}

func newHttpInternalServer(a *App) (*httpInternalServer, error) {
	cfg := a.hTTPConfig
	lc, ok := cfg.Groups["internal"]
	if !ok {
		return nil, fmt.Errorf("http: group %q declared in the spec but missing from HTTPConfig.Groups", "internal")
	}
	s := &httpInternalServer{app: a, lc: lc}
	mux := http.NewServeMux()
	mux.HandleFunc("POST /replicate/{shard}", s.handleReplicate)
	var handler http.Handler = mux
	handler = a.auth.Middleware(handler)
	handler = a.requestID.Middleware(handler)
	handler = a.recover2.Middleware(handler)
	s.srv = &http.Server{
		Addr:         net.JoinHostPort(lc.IP, strconv.FormatUint(uint64(lc.Port), 10)),
		Handler:      handler,
		ReadTimeout:  lc.ReadTimeout,
		WriteTimeout: lc.WriteTimeout,
		IdleTimeout:  lc.IdleTimeout,
	}
	return s, nil
}

func (s *httpInternalServer) handleReplicate(w http.ResponseWriter, r *http.Request) {
	req := &api.ReplicateReq{}
	req.Shard = r.PathValue("shard")
	user, err := s.app.userExtractor.Extract(r)
	if err != nil {
		httpWriteFailure(w, "api.Replicate", "POST /replicate/{shard}", err)
		return
	}
	res, err := api.Replicate(r.Context(), req, user)
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "api.Replicate", "POST /replicate/{shard}", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpInternalServer) run(ctx context.Context) error {
	ln, err := net.Listen("tcp", s.srv.Addr)
	if err != nil {
		return fmt.Errorf("http:internal: listen %s: %w", s.srv.Addr, err)
	}
	s.ready.Store(true)
	serveErr := make(chan error, 1)
	go func() {
		var err error
		if s.lc.CertFile != "" && s.lc.KeyFile != "" {
			err = s.srv.ServeTLS(ln, s.lc.CertFile, s.lc.KeyFile)
		} else {
			err = s.srv.Serve(ln)
		}
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			serveErr <- err
			return
		}
		serveErr <- nil
	}()
	select {
	case <-ctx.Done():
		return nil
	case err := <-serveErr:
		return err
	}
}

// httpTelemetryServer serves group "telemetry"'s //servo: routes. It is generated
// machinery, not a graph node: its dependencies are ordinary singletons
// on the App, resolved once at construction.
type httpTelemetryServer struct {
	app *App
	lc  servo.HTTPListener
	srv *http.Server
	// ready flips once the listener is bound, which is the precise moment
	// Ready starts reporting ok for the "http:telemetry" node.
	ready atomic.Bool
}

func newHttpTelemetryServer(a *App) (*httpTelemetryServer, error) {
	cfg := a.hTTPConfig
	lc, ok := cfg.Groups["telemetry"]
	if !ok {
		return nil, fmt.Errorf("http: group %q declared in the spec but missing from HTTPConfig.Groups", "telemetry")
	}
	s := &httpTelemetryServer{app: a, lc: lc}
	mux := http.NewServeMux()
	mux.HandleFunc("GET /healthz", s.handleHealthz)
	var handler http.Handler = mux
	handler = a.requestID.Middleware(handler)
	handler = a.recover2.Middleware(handler)
	s.srv = &http.Server{
		Addr:         net.JoinHostPort(lc.IP, strconv.FormatUint(uint64(lc.Port), 10)),
		Handler:      handler,
		ReadTimeout:  lc.ReadTimeout,
		WriteTimeout: lc.WriteTimeout,
		IdleTimeout:  lc.IdleTimeout,
	}
	return s, nil
}

func (s *httpTelemetryServer) handleHealthz(w http.ResponseWriter, r *http.Request) {
	res, err := api.Healthz(r.Context())
	if err != nil {
		var hs servo.HTTPStatus
		if errors.As(err, &hs) && hs.Code() < 400 {
			// A 2xx or 3xx status in the error position is the contract's
			// way of picking a success or redirect code.
			httpRespond(w, hs.Code(), res)
			return
		}
		httpWriteFailure(w, "api.Healthz", "GET /healthz", err)
		return
	}
	httpRespond(w, http.StatusOK, res)
}

func (s *httpTelemetryServer) run(ctx context.Context) error {
	ln, err := net.Listen("tcp", s.srv.Addr)
	if err != nil {
		return fmt.Errorf("http:telemetry: listen %s: %w", s.srv.Addr, err)
	}
	s.ready.Store(true)
	serveErr := make(chan error, 1)
	go func() {
		var err error
		if s.lc.CertFile != "" && s.lc.KeyFile != "" {
			err = s.srv.ServeTLS(ln, s.lc.CertFile, s.lc.KeyFile)
		} else {
			err = s.srv.Serve(ln)
		}
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			serveErr <- err
			return
		}
		serveErr <- nil
	}()
	select {
	case <-ctx.Done():
		return nil
	case err := <-serveErr:
		return err
	}
}

// httpRespond writes one success response; a nil response means status only,
// no body. Encoding lives in the runtime's sealed Response family, so a
// handler may return any of its kinds through this one helper.
func httpRespond(w http.ResponseWriter, code int, res servo.Response) {
	if res == nil {
		w.WriteHeader(code)
		return
	}
	if err := servo.WriteResponse(w, code, res); err != nil {
		slog.Error("servo: writing response failed", "error", err)
	}
}

// httpWriteFailure maps a handler or extractor error onto the response: a status in
// the chain picks the code, 4xx bodies carry the message, 5xx bodies only
// the canonical text — the wrapped detail is for the log, not the client.
func httpWriteFailure(w http.ResponseWriter, handler, route string, err error) {
	var hs servo.HTTPStatus
	if !errors.As(err, &hs) {
		slog.Error("servo: handler "+handler+" failed", "route", route, "error", err)
		httpWriteError(w, http.StatusInternalServerError, "Internal Server Error")
		return
	}
	code := hs.Code()
	if code >= 500 {
		slog.Error("servo: handler "+handler+" failed", "route", route, "status", code, "error", err)
		httpWriteError(w, code, hs.Error())
		return
	}
	httpWriteError(w, code, err.Error())
}

func httpWriteError(w http.ResponseWriter, code int, msg string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(struct {
		Error string `json:"error"`
	}{Error: msg})
}

func New(ctx context.Context) (*App, error) {
	a := &App{}

	hTTPConfig, err := api.NewHTTPConfig()
	if err != nil {
		return nil, err
	}
	a.hTTPConfig = hTTPConfig

	userExtractor := mw.NewUserExtractor()
	a.userExtractor = userExtractor

	recover2 := middleware.NewRecover()
	a.recover2 = recover2

	requestID := middleware.NewRequestID()
	a.requestID = requestID

	cORSConfig := api.NewCORSConfig()
	a.cORSConfig = cORSConfig

	cors, err := middleware.NewCORS(cORSConfig)
	if err != nil {
		return nil, err
	}
	a.cors = cors

	auth := mw.NewAuth()
	a.auth = auth

	store := store.New()
	a.store = store

	httpServer, err := newHttpServer(a)
	if err != nil {
		report := a.Shutdown(ctx)
		return nil, errors.Join(err, report)
	}
	a.httpServer = httpServer

	httpInternalServer, err := newHttpInternalServer(a)
	if err != nil {
		report := a.Shutdown(ctx)
		return nil, errors.Join(err, report)
	}
	a.httpInternalServer = httpInternalServer

	httpTelemetryServer, err := newHttpTelemetryServer(a)
	if err != nil {
		report := a.Shutdown(ctx)
		return nil, errors.Join(err, report)
	}
	a.httpTelemetryServer = httpTelemetryServer

	return a, nil
}

func (a *App) stopHttpServer(ctx context.Context) servo.NodeResult {
	a.httpServerStopOnce.Do(func() {
		if a.httpServer == nil {
			a.httpServerStopResult = servo.NodeResult{Name: "http", Status: servo.StatusOK}
			return
		}
		a.httpServerStopResult = servo.RunStop(ctx, servo.DefaultStopBudget, "http", a.httpServer.srv.Shutdown)
	})
	return a.httpServerStopResult
}

func (a *App) stopHttpInternalServer(ctx context.Context) servo.NodeResult {
	a.httpInternalServerStopOnce.Do(func() {
		if a.httpInternalServer == nil {
			a.httpInternalServerStopResult = servo.NodeResult{Name: "http:internal", Status: servo.StatusOK}
			return
		}
		a.httpInternalServerStopResult = servo.RunStop(ctx, servo.DefaultStopBudget, "http:internal", a.httpInternalServer.srv.Shutdown)
	})
	return a.httpInternalServerStopResult
}

func (a *App) stopHttpTelemetryServer(ctx context.Context) servo.NodeResult {
	a.httpTelemetryServerStopOnce.Do(func() {
		if a.httpTelemetryServer == nil {
			a.httpTelemetryServerStopResult = servo.NodeResult{Name: "http:telemetry", Status: servo.StatusOK}
			return
		}
		a.httpTelemetryServerStopResult = servo.RunStop(ctx, servo.DefaultStopBudget, "http:telemetry", a.httpTelemetryServer.srv.Shutdown)
	})
	return a.httpTelemetryServerStopResult
}

func (a *App) Run(ctx context.Context) error {
	g, gctx := errgroup.WithContext(ctx)
	g.Go(func() error { return a.httpServer.run(gctx) })
	g.Go(func() error { return a.httpInternalServer.run(gctx) })
	g.Go(func() error { return a.httpTelemetryServer.run(gctx) })
	return g.Wait()
}

func (a *App) Shutdown(ctx context.Context) servo.Report {
	forceExit := make(chan os.Signal, 1)
	signal.Notify(forceExit, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(forceExit)
	watcherDone := make(chan struct{})
	defer close(watcherDone)
	go func() {
		select {
		case <-forceExit:
			os.Exit(1)
		case <-watcherDone:
		}
	}()

	var nodes []servo.NodeResult
	nodes = append(nodes, a.stopHttpServer(ctx))
	nodes = append(nodes, a.stopHttpInternalServer(ctx))
	nodes = append(nodes, a.stopHttpTelemetryServer(ctx))
	return servo.Report{Nodes: nodes}
}

func (a *App) Health(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Ready(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	if a.httpServer != nil && a.httpServer.ready.Load() {
		nodes = append(nodes, servo.NodeResult{Name: "http", Status: servo.StatusOK})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "http", Status: servo.StatusFailed, Err: errors.New("http: not accepting connections yet")})
	}
	if a.httpInternalServer != nil && a.httpInternalServer.ready.Load() {
		nodes = append(nodes, servo.NodeResult{Name: "http:internal", Status: servo.StatusOK})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "http:internal", Status: servo.StatusFailed, Err: errors.New("http:internal: not accepting connections yet")})
	}
	if a.httpTelemetryServer != nil && a.httpTelemetryServer.ready.Load() {
		nodes = append(nodes, servo.NodeResult{Name: "http:telemetry", Status: servo.StatusOK})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "http:telemetry", Status: servo.StatusFailed, Err: errors.New("http:telemetry: not accepting connections yet")})
	}
	return servo.Report{Nodes: nodes}
}

func (a *App) Graph() servo.Graph {
	return servo.Graph{Nodes: []servo.GraphNode{
		{Type: "*github.com/okian/servo/v3/servo.HTTPConfig", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "api/api.go:38:6"},
		{Type: "*example.com/servohttp/mw.UserExtractor", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "mw/mw.go:35:6"},
		{Type: "*github.com/okian/servo/v3/middleware.Recover", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "/Users/kian/servo/middleware/recover.go:17:6"},
		{Type: "*github.com/okian/servo/v3/middleware.RequestID", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "/Users/kian/servo/middleware/requestid.go:17:6"},
		{Type: "*github.com/okian/servo/v3/middleware.CORSConfig", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "api/api.go:25:6"},
		{Type: "*github.com/okian/servo/v3/middleware.CORS", Level: 2, Deps: []string{"*github.com/okian/servo/v3/middleware.CORSConfig"}, Capabilities: nil, Binding: "sole candidate", Pos: "/Users/kian/servo/middleware/cors.go:44:6"},
		{Type: "*example.com/servohttp/mw.Auth", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "mw/mw.go:17:6"},
		{Type: "*example.com/servohttp/store.Store", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "store/store.go:22:6"},
	}}
}

func (a *App) Report() servo.StartupReport {
	return a.startupReport
}
