//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// Resolved graph:
//
//	[L1] *github.com/okian/servo/v3/servo.HTTPConfig
//	      deps: none
//	      capabilities: none | binding: sole candidate | api/api.go:23:6
//	[L1] *example.com/servohttp/store.Store
//	      deps: none
//	      capabilities: none | binding: sole candidate | store/store.go:22:6
//
// http (servo.HTTP() at cmd/app/spec.go:15:3):
//
//	config: *github.com/okian/servo/v3/servo.HTTPConfig
//	POST /feedback -> api.Feedback (api/api.go:135:1)
//	      deps: none
//	POST /order/{category}/ -> api.Order (api/api.go:62:1)
//	      deps: *example.com/servohttp/store.Store
//	GET /search -> api.Search (api/api.go:99:1)
//	      deps: none
//	GET /whoami -> api.Whoami (api/api.go:114:1)
//	      deps: none
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"sync"
	"sync/atomic"
	"syscall"

	"example.com/servohttp/api"
	"example.com/servohttp/store"
	"github.com/okian/servo/v3/servo"
)

type App struct {
	hTTPConfig           *servo.HTTPConfig
	store                *store.Store
	httpServer           *httpServer
	httpServerStopOnce   sync.Once
	httpServerStopResult servo.NodeResult
	startupReport        servo.StartupReport
}

// httpServer serves the //servo: routes declared across this module. It is
// generated machinery, not a graph node: its dependencies are ordinary
// singletons on the App, resolved once at construction.
type httpServer struct {
	app     *App
	cfg     *servo.HTTPConfig
	srv     *http.Server
	maxBody int64
	// ready flips once the listener is bound, which is the precise moment
	// Ready starts reporting ok for the "http" node.
	ready atomic.Bool
}

const defaultMaxBodyBytes = 1 << 20

func newHttpServer(a *App) *httpServer {
	cfg := a.hTTPConfig
	s := &httpServer{app: a, cfg: cfg}
	s.maxBody = cfg.MaxBodyBytes
	if s.maxBody <= 0 {
		s.maxBody = defaultMaxBodyBytes
	}
	mux := http.NewServeMux()
	mux.HandleFunc("POST /feedback", s.handleFeedback)
	mux.HandleFunc("POST /order/{category}/", s.handleOrder)
	mux.HandleFunc("GET /search", s.handleSearch)
	mux.HandleFunc("GET /whoami", s.handleWhoami)
	s.srv = &http.Server{
		Addr:         net.JoinHostPort(cfg.IP, strconv.FormatUint(uint64(cfg.Port), 10)),
		Handler:      mux,
		ReadTimeout:  cfg.ReadTimeout,
		WriteTimeout: cfg.WriteTimeout,
		IdleTimeout:  cfg.IdleTimeout,
	}
	return s
}

func (s *httpServer) handleFeedback(w http.ResponseWriter, r *http.Request) {
	req := &api.FeedbackReq{}
	r.Body = http.MaxBytesReader(w, r.Body, s.maxBody)
	// ParseMultipartForm falls through to ParseForm on urlencoded
	// bodies, reporting ErrNotMultipart after already parsing them.
	if err := r.ParseMultipartForm(s.maxBody); err != nil && !errors.Is(err, http.ErrNotMultipart) {
		s.writeError(w, http.StatusBadRequest, "malformed form body")
		return
	}
	req.Subject = r.PostForm.Get("subject")
	if raw := r.PostForm.Get("stars"); raw != "" {
		v, err := strconv.ParseInt(raw, 10, 0)
		if err != nil {
			s.writeError(w, http.StatusBadRequest, "form value \"stars\" is not a valid int")
			return
		}
		req.Stars = int(v)
	}
	res, err := api.Feedback(r.Context(), req)
	if err != nil {
		var hs servo.HTTPStatus
		if !errors.As(err, &hs) {
			slog.Error("servo: handler api.Feedback failed", "route", "POST /feedback", "error", err)
			s.writeError(w, http.StatusInternalServerError, "Internal Server Error")
			return
		}
		code := hs.Code()
		switch {
		case code < 300:
			// A 2xx status in the error position is the contract's way of
			// picking a success code other than 200.
			httpRespond(s, w, code, res)
		case code < 500:
			s.writeError(w, code, err.Error())
		default:
			// 5xx bodies carry only the canonical text; the wrapped detail
			// is for the log, not the client.
			slog.Error("servo: handler api.Feedback failed", "route", "POST /feedback", "error", err)
			s.writeError(w, code, hs.Error())
		}
		return
	}
	httpRespond(s, w, http.StatusOK, res)
}

func (s *httpServer) handleOrder(w http.ResponseWriter, r *http.Request) {
	req := &api.OrderReq{}
	// The body decodes first, so the explicitly bound sources below
	// overwrite anything it could smuggle into a same-named field.
	r.Body = http.MaxBytesReader(w, r.Body, s.maxBody)
	if err := json.NewDecoder(r.Body).Decode(req); err != nil {
		s.writeError(w, http.StatusBadRequest, "malformed request body")
		return
	}
	q := r.URL.Query()
	req.Category = r.PathValue("category")
	if raw := q.Get("priority"); raw != "" {
		v, err := strconv.ParseInt(raw, 10, 0)
		if err != nil {
			s.writeError(w, http.StatusBadRequest, "query parameter \"priority\" is not a valid int")
			return
		}
		req.Priority = int(v)
	}
	res, err := api.Order(r.Context(), req, s.app.store)
	if err != nil {
		var hs servo.HTTPStatus
		if !errors.As(err, &hs) {
			slog.Error("servo: handler api.Order failed", "route", "POST /order/{category}/", "error", err)
			s.writeError(w, http.StatusInternalServerError, "Internal Server Error")
			return
		}
		code := hs.Code()
		switch {
		case code < 300:
			// A 2xx status in the error position is the contract's way of
			// picking a success code other than 200.
			httpRespond(s, w, code, res)
		case code < 500:
			s.writeError(w, code, err.Error())
		default:
			// 5xx bodies carry only the canonical text; the wrapped detail
			// is for the log, not the client.
			slog.Error("servo: handler api.Order failed", "route", "POST /order/{category}/", "error", err)
			s.writeError(w, code, hs.Error())
		}
		return
	}
	httpRespond(s, w, http.StatusOK, res)
}

func (s *httpServer) handleSearch(w http.ResponseWriter, r *http.Request) {
	req := &api.SearchReq{}
	q := r.URL.Query()
	req.Q = q.Get("q")
	if raw := q.Get("limit"); raw != "" {
		v, err := strconv.ParseUint(raw, 10, 16)
		if err != nil {
			s.writeError(w, http.StatusBadRequest, "query parameter \"limit\" is not a valid uint16")
			return
		}
		req.Limit = uint16(v)
	}
	if raw := q.Get("ratio"); raw != "" {
		v, err := strconv.ParseFloat(raw, 64)
		if err != nil {
			s.writeError(w, http.StatusBadRequest, "query parameter \"ratio\" is not a valid float64")
			return
		}
		req.Ratio = v
	}
	if raw := q.Get("exact"); raw != "" {
		v, err := strconv.ParseBool(raw)
		if err != nil {
			s.writeError(w, http.StatusBadRequest, "query parameter \"exact\" is not a valid bool")
			return
		}
		req.Exact = v
	}
	res, err := api.Search(r.Context(), req)
	if err != nil {
		var hs servo.HTTPStatus
		if !errors.As(err, &hs) {
			slog.Error("servo: handler api.Search failed", "route", "GET /search", "error", err)
			s.writeError(w, http.StatusInternalServerError, "Internal Server Error")
			return
		}
		code := hs.Code()
		switch {
		case code < 300:
			// A 2xx status in the error position is the contract's way of
			// picking a success code other than 200.
			httpRespond(s, w, code, res)
		case code < 500:
			s.writeError(w, code, err.Error())
		default:
			// 5xx bodies carry only the canonical text; the wrapped detail
			// is for the log, not the client.
			slog.Error("servo: handler api.Search failed", "route", "GET /search", "error", err)
			s.writeError(w, code, hs.Error())
		}
		return
	}
	httpRespond(s, w, http.StatusOK, res)
}

func (s *httpServer) handleWhoami(w http.ResponseWriter, r *http.Request) {
	req := &api.WhoamiReq{}
	req.User = r.Header.Get("X-User")
	res, err := api.Whoami(r.Context(), req)
	if err != nil {
		var hs servo.HTTPStatus
		if !errors.As(err, &hs) {
			slog.Error("servo: handler api.Whoami failed", "route", "GET /whoami", "error", err)
			s.writeError(w, http.StatusInternalServerError, "Internal Server Error")
			return
		}
		code := hs.Code()
		switch {
		case code < 300:
			// A 2xx status in the error position is the contract's way of
			// picking a success code other than 200.
			httpRespond(s, w, code, res)
		case code < 500:
			s.writeError(w, code, err.Error())
		default:
			// 5xx bodies carry only the canonical text; the wrapped detail
			// is for the log, not the client.
			slog.Error("servo: handler api.Whoami failed", "route", "GET /whoami", "error", err)
			s.writeError(w, code, hs.Error())
		}
		return
	}
	httpRespond(s, w, http.StatusOK, res)
}

// httpRespond writes one success response; a nil Json means status only, no body.
func httpRespond[T any](s *httpServer, w http.ResponseWriter, code int, res servo.Json[T]) {
	if res == nil {
		w.WriteHeader(code)
		return
	}
	s.writeJSON(w, code, res.Value())
}

func (s *httpServer) writeJSON(w http.ResponseWriter, code int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	if err := json.NewEncoder(w).Encode(payload); err != nil {
		slog.Error("servo: encoding response failed", "error", err)
	}
}

func (s *httpServer) writeError(w http.ResponseWriter, code int, msg string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(struct {
		Error string `json:"error"`
	}{Error: msg})
}

func (s *httpServer) run(ctx context.Context) error {
	ln, err := net.Listen("tcp", s.srv.Addr)
	if err != nil {
		return fmt.Errorf("http: listen %s: %w", s.srv.Addr, err)
	}
	s.ready.Store(true)
	serveErr := make(chan error, 1)
	go func() {
		var err error
		if s.cfg.CertFile != "" && s.cfg.KeyFile != "" {
			err = s.srv.ServeTLS(ln, s.cfg.CertFile, s.cfg.KeyFile)
		} else {
			err = s.srv.Serve(ln)
		}
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			serveErr <- err
			return
		}
		serveErr <- nil
	}()
	select {
	case <-ctx.Done():
		return nil
	case err := <-serveErr:
		return err
	}
}

func New(ctx context.Context) (*App, error) {
	a := &App{}

	hTTPConfig, err := api.NewHTTPConfig()
	if err != nil {
		return nil, err
	}
	a.hTTPConfig = hTTPConfig

	store := store.New()
	a.store = store

	a.httpServer = newHttpServer(a)

	return a, nil
}

func (a *App) stopHttpServer(ctx context.Context) servo.NodeResult {
	a.httpServerStopOnce.Do(func() {
		if a.httpServer == nil {
			a.httpServerStopResult = servo.NodeResult{Name: "http", Status: servo.StatusOK}
			return
		}
		a.httpServerStopResult = servo.RunStop(ctx, servo.DefaultStopBudget, "http", a.httpServer.srv.Shutdown)
	})
	return a.httpServerStopResult
}

func (a *App) Run(ctx context.Context) error {
	return a.httpServer.run(ctx)
}

func (a *App) Shutdown(ctx context.Context) servo.Report {
	forceExit := make(chan os.Signal, 1)
	signal.Notify(forceExit, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(forceExit)
	watcherDone := make(chan struct{})
	defer close(watcherDone)
	go func() {
		select {
		case <-forceExit:
			os.Exit(1)
		case <-watcherDone:
		}
	}()

	var nodes []servo.NodeResult
	nodes = append(nodes, a.stopHttpServer(ctx))
	return servo.Report{Nodes: nodes}
}

func (a *App) Health(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	return servo.Report{Nodes: nodes}
}

func (a *App) Ready(ctx context.Context) servo.Report {
	var nodes []servo.NodeResult
	if a.httpServer != nil && a.httpServer.ready.Load() {
		nodes = append(nodes, servo.NodeResult{Name: "http", Status: servo.StatusOK})
	} else {
		nodes = append(nodes, servo.NodeResult{Name: "http", Status: servo.StatusFailed, Err: errors.New("http: not accepting connections yet")})
	}
	return servo.Report{Nodes: nodes}
}

func (a *App) Graph() servo.Graph {
	return servo.Graph{Nodes: []servo.GraphNode{
		{Type: "*github.com/okian/servo/v3/servo.HTTPConfig", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "api/api.go:23:6"},
		{Type: "*example.com/servohttp/store.Store", Level: 1, Deps: nil, Capabilities: nil, Binding: "sole candidate", Pos: "store/store.go:22:6"},
	}}
}

func (a *App) Report() servo.StartupReport {
	return a.startupReport
}
