//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// ServoConfig fills Config from the process environment.
// Settings:
//
//	NATS_URL string, required
package natsbroker

import (
	"fmt"
	"os"
	"strings"
)

// ServoConfig builds Config. Precedence per setting: default, then the NATS_* environment
// variable — the environment always wins.
func ServoConfig() (Config, error) {
	var cfg Config
	var missing []string

	// url — NATS_URL (required)
	if v, ok := os.LookupEnv("NATS_URL"); ok {
		cfg.URL = v
	} else {
		missing = append(missing, "NATS_URL")
	}

	if len(missing) > 0 {
		return Config{}, fmt.Errorf("natsbroker: missing required configuration: %s", strings.Join(missing, ", "))
	}
	return cfg, nil
}
