//go:build !servoinject

// Code generated by servo generate. DO NOT EDIT.
//
// ServoConfig fills Config from the process environment.
// Settings:
//
//	OBS_LOG_LEVEL     string, default info
//	OBS_OTLP_ENDPOINT string
package observability

import (
	"os"
)

// ServoConfig builds Config. Precedence per setting: default, then the OBS_* environment
// variable — the environment always wins.
func ServoConfig() (Config, error) {
	var cfg Config

	// log_level — OBS_LOG_LEVEL
	cfg.LogLevel = "info"
	if v, ok := os.LookupEnv("OBS_LOG_LEVEL"); ok {
		cfg.LogLevel = v
	}

	// otlp_endpoint — OBS_OTLP_ENDPOINT
	if v, ok := os.LookupEnv("OBS_OTLP_ENDPOINT"); ok {
		cfg.OTLPEndpoint = v
	}
	return cfg, nil
}
